"""Contrato público de tokens do Design System."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from types import MappingProxyType
from typing import Iterator, Mapping


class TokenLevel(str, Enum):
    SEMANTIC = "semantic"
    COMPONENT = "component"


class TokenKind(str, Enum):
    COLOR = "color"
    GRADIENT = "gradient"


class VisualState(str, Enum):
    NORMAL = "normal"
    HOVER = "hover"
    PRESSED = "pressed"
    SELECTED = "selected"
    FOCUSED = "focused"
    KEYBOARD_FOCUS = "keyboard_focus"
    CHECKED = "checked"
    DISABLED = "disabled"
    CORRECT = "correct"
    INCORRECT = "incorrect"
    STRUCK = "struck"


@dataclass(frozen=True, slots=True)
class TokenSpec:
    path: str
    level: TokenLevel
    kind: TokenKind = TokenKind.COLOR

    def __post_init__(self) -> None:
        parts = self.path.split(".")
        if len(parts) < 2 or any(not part or not part.isidentifier() for part in parts):
            raise ValueError(f"Caminho de token inválido: {self.path!r}")


_SEMANTIC_COLOR_PATHS = (
    "canvas.app", "canvas.dialog", "canvas.inset",
    "surface.primary", "surface.secondary", "surface.tertiary", "surface.elevated",
    "surface.inset", "surface.hover", "surface.pressed", "surface.selected", "surface.disabled",
    "surface.interactive", "surface.inverse", "surface.focused",
    "text.primary", "text.secondary", "text.muted", "text.disabled", "text.inverse",
    "text.link", "text.on_action", "text.on_feedback", "text.control", "text.selected",
    "text.choice", "text.header", "text.interactive_hover", "text.selection_accent",
    "text.control_subtle", "text.readonly", "text.popup",
    "border.default", "border.subtle", "border.strong", "border.hover", "border.active",
    "border.selected", "border.disabled", "border.focus", "border.control_subtle", "border.control_hover",
    "border.divider", "border.divider_strong", "border.grid", "border.control_indicator", "border.checked",
    "action.primary", "action.primary_hover", "action.primary_pressed", "action.primary_disabled",
    "action.secondary", "action.secondary_hover", "action.secondary_pressed", "action.secondary_disabled",
    "action.ghost", "action.ghost_hover", "action.checked", "action.destructive", "action.destructive_hover",
    "feedback.success_surface", "feedback.success_text", "feedback.success_border", "feedback.success_icon",
    "feedback.warning_surface", "feedback.warning_text", "feedback.warning_border", "feedback.warning_icon",
    "feedback.danger_surface", "feedback.danger_text", "feedback.danger_border", "feedback.danger_icon",
    "feedback.info_surface", "feedback.info_text", "feedback.info_border", "feedback.info_icon",
    "focus.ring", "focus.keyboard",
    "icon.default", "icon.muted", "icon.disabled", "icon.action", "icon.highlight", "icon.configuration",
    "overlay.scrim", "overlay.light", "overlay.dark", "overlay.selection", "overlay.selection_subtle",
    "glow.primary", "glow.focus", "glow.success", "glow.danger",
)

_SEMANTIC_GRADIENT_PATHS = (
    "gradient.action_primary", "gradient.action_primary_hover", "gradient.surface_elevated",
    "gradient.hero", "gradient.progress", "gradient.control_input",
    "gradient.control_header", "gradient.control_tab", "gradient.control_selected",
)

_COMPONENT_COLOR_PATHS = (
    "answer.normal_surface", "answer.normal_border", "answer.normal_text",
    "answer.hover_surface", "answer.hover_border",
    "answer.pressed_surface", "answer.pressed_border",
    "answer.selected_surface", "answer.selected_border", "answer.selected_text",
    "answer.focused_border", "answer.keyboard_focus_border", "answer.checked_indicator",
    "answer.indicator_surface", "answer.indicator_border", "answer.indicator_hover_border",
    "answer.indicator_checked_border", "answer.indicator_text",
    "answer.disabled_surface", "answer.disabled_border", "answer.disabled_text",
    "answer.correct_surface", "answer.correct_border", "answer.correct_text",
    "answer.incorrect_surface", "answer.incorrect_border", "answer.incorrect_text",
    "answer.struck_surface", "answer.struck_border", "answer.struck_text",
    "answer.struck_hover_surface", "answer.struck_hover_border",
    "answer.eliminate_text", "answer.eliminate_hover_surface", "answer.eliminate_hover_text",
    "answer.eliminate_checked_surface", "answer.eliminate_checked_text",
    "answer.eliminate_checked_border",
    "answer.explanation_surface", "answer.explanation_border",
    "answer.explanation_title_text", "answer.explanation_text",
    "answer.editor_surface", "answer.editor_border", "answer.editor_text",
    "answer.editor_selection",
    "answer.edit_action_surface", "answer.edit_action_hover_surface",
    "answer.edit_action_hover_text", "answer.edit_action_hover_border",
    "answer.save_action_surface", "answer.save_action_text", "answer.save_action_border",
    "answer.cancel_action_surface",
    "answer.primary_action_border", "answer.primary_action_hover_border",
    "feedback.queue_detail_surface", "feedback.queue_detail_text", "feedback.queue_detail_border",
    "summary.canvas", "summary.title_text", "summary.subtitle_text",
    "summary.metric_surface", "summary.metric_border",
    "summary.metric_label_text", "summary.metric_value_text",
    "summary.detail_surface", "summary.detail_text", "summary.detail_border",
    "summary.table_surface", "summary.table_border",
    "summary.review_surface", "summary.review_border",
    "summary.review_title_text", "summary.review_text",
    "summary.adaptive_surface", "summary.adaptive_border",
    "summary.adaptive_title_text", "summary.adaptive_text",
    "summary.effectiveness_surface", "summary.effectiveness_border",
    "summary.effectiveness_title_text",
    "summary.effectiveness_metric_surface", "summary.effectiveness_metric_border",
    "summary.effectiveness_metric_label_text", "summary.effectiveness_metric_value_text",
    "summary.mock_exam_section_title_text",
    "summary.mock_exam_notice_surface", "summary.mock_exam_notice_text",
    "summary.mock_exam_notice_border",
    "progress.track", "progress.border", "progress.fill", "progress.text", "progress.complete", "progress.warning",
    "progress.session_text", "progress.session_track",
    "session.title_text", "session.subtitle_text", "session.panel_surface",
    "session.overview_border", "session.eyebrow_text", "session.cycle_text",
    "session.metric_surface", "session.metric_border", "session.metric_label_text",
    "session.metric_value_text", "session.metric_success_text",
    "session.metric_danger_text", "session.metric_warning_text",
    "session.discipline_text", "session.meta_text", "session.question_index_text",
    "session.statement_surface", "session.statement_border", "session.statement_text",
    "session.navigation_surface",
    "session.navigation_text",
    "session.navigation_border",
    "session.navigation_hover_surface",
    "session.navigation_hover_text",
    "session.navigation_hover_border",
    "session.timer_surface",
    "session.timer_text",
    "session.timer_border",
    "session.action_panel_surface",
    "session.action_panel_border",
    "session.skip_surface",
    "session.skip_text",
    "session.skip_border",
    "session.skip_hover_surface",
    "session.skip_hover_text",
    "session.skip_hover_border",
    "session.end_surface",
    "session.end_text",
    "session.end_border",
    "session.end_hover_surface",
    "session.end_hover_text",
    "session.end_hover_border",
    "session.flag_indicator_surface",
    "session.doubt_text",
    "session.doubt_checked_text",
    "session.doubt_indicator_border",
    "session.doubt_indicator_hover_border",
    "session.doubt_indicator_checked_surface",
    "session.doubt_indicator_checked_border",
    "session.doubt_indicator_disabled_surface",
    "session.doubt_indicator_disabled_border",
    "session.analysis_text",
    "session.analysis_checked_text",
    "session.analysis_indicator_border",
    "session.analysis_indicator_hover_border",
    "session.analysis_indicator_checked_surface",
    "session.analysis_indicator_checked_border",
    "calendar.surface", "calendar.today_surface", "calendar.today_border", "calendar.today_text",
    "calendar.selected_surface", "calendar.selected_text", "calendar.week_predicted_surface",
    "calendar.week_predicted_border", "calendar.week_predicted_text", "calendar.weekend_text",
    "calendar.outside_month_text", "calendar.border", "calendar.text", "calendar.title_text",
    "calendar.badge_surface", "calendar.badge_text", "calendar.badge_border",
    "calendar.legend_today", "calendar.legend_late", "calendar.legend_scheduled",
    "calendar.navigation_surface", "calendar.navigation_hover_surface",
    "calendar.input_surface", "calendar.input_border",
    "calendar.late_surface", "calendar.late_text",
    "calendar.scheduled_surface", "calendar.scheduled_text",
    "calendar.forecast_toggle_surface", "calendar.forecast_toggle_text",
    "calendar.forecast_toggle_border", "calendar.forecast_toggle_hover_surface",
    "calendar.forecast_toggle_hover_text", "calendar.forecast_toggle_hover_border",
    "calendar.forecast_toggle_checked_surface", "calendar.forecast_toggle_checked_border",
    "calendar.forecast_action_text", "calendar.forecast_meta_text",
    "calendar.forecast_panel_surface", "calendar.forecast_panel_border",
    "calendar.forecast_title_text", "calendar.forecast_notice_text",
    "calendar.forecast_today_surface", "calendar.forecast_past_surface",
    "calendar.forecast_past_border", "calendar.forecast_count_surface",
    "calendar.forecast_count_text", "calendar.forecast_badge_surface",
    "calendar.forecast_badge_text", "calendar.forecast_badge_border",
    "calendar.forecast_card_surface", "calendar.forecast_card_accent",
    "calendar.forecast_review", "calendar.forecast_completed",
    "calendar.forecast_recommendation", "calendar.forecast_simulation",
    "calendar.forecast_discipline_text", "calendar.forecast_card_text",
    "calendar.forecast_open_text", "calendar.forecast_open_hover_surface",
    "calendar.forecast_open_hover_border", "calendar.forecast_empty_text",
    "chart.axis", "chart.grid", "chart.label", "chart.series_1", "chart.series_2", "chart.series_3",
    "chart.series_4", "chart.series_5", "chart.series_6", "chart.positive", "chart.negative",
    "focus_mode.canvas", "focus_mode.panel", "focus_mode.panel_active", "focus_mode.text",
    "focus_mode.timer", "focus_mode.border",
    "focus_mode.secondary_text", "focus_mode.section_text", "focus_mode.meta_text",
    "focus_mode.panel_active_border",
    "focus_mode.hero_surface", "focus_mode.hero_border",
    "focus_mode.hero_eyebrow_text", "focus_mode.hero_value_text", "focus_mode.hero_status_text",
    "focus_mode.mini_surface", "focus_mode.mini_border",
    "focus_mode.mini_label_text", "focus_mode.mini_value_text",
    "focus_mode.secondary_action_surface", "focus_mode.secondary_action_text",
    "focus_mode.secondary_action_border", "focus_mode.secondary_action_hover_surface",
    "focus_mode.secondary_action_hover_text", "focus_mode.secondary_action_hover_border",
    "focus_mode.action", "focus_mode.action_border", "focus_mode.action_hover_border",
    "focus_mode.action_pressed_border",
    "focus_mode.danger", "focus_mode.danger_text", "focus_mode.danger_border",
    "focus_mode.danger_hover_surface", "focus_mode.danger_hover_border",
    "focus_mode.progress_track", "focus_mode.progress_fill", "focus_mode.progress_border",
    "focus_mode.optional_surface", "focus_mode.optional_border",
    "focus_mode.notice_surface", "focus_mode.notice_text", "focus_mode.notice_border",
    "focus_mode.session_bar_surface", "focus_mode.session_bar_border",
    "focus_mode.session_bar_status_text",
    "focus_mode.session_bar_button_surface", "focus_mode.session_bar_button_text",
    "focus_mode.session_bar_button_border",
    "focus_mode.session_bar_button_hover_surface", "focus_mode.session_bar_button_hover_text",
    "focus_mode.session_bar_button_hover_border",
    "post_focus.dialog_title_text",
    "post_focus.dialog_subtitle_text",
    "post_focus.hero_surface",
    "post_focus.hero_border",
    "post_focus.eyebrow_text",
    "post_focus.time_text",
    "post_focus.meta_text",
    "post_focus.mini_surface",
    "post_focus.mini_border",
    "post_focus.mini_label_text",
    "post_focus.mini_value_text",
    "post_focus.content_surface",
    "post_focus.content_border",
    "post_focus.strong_text",
    "post_focus.result_surface",
    "post_focus.result_border",
    "post_focus.result_value_text",
    "post_focus.continue_surface",
    "post_focus.continue_text",
    "post_focus.continue_border",
    "post_focus.continue_hover_surface",
    "post_focus.continue_hover_border",
    "post_focus.primary_surface",
    "post_focus.primary_border",
    "post_focus.primary_hover_surface",
    "post_focus.primary_hover_border",
    "post_focus.secondary_surface",
    "post_focus.secondary_text",
    "post_focus.secondary_border",
    "post_focus.secondary_hover_surface",
    "post_focus.secondary_hover_border",
    "post_focus.secondary_disabled_text",
    "post_focus.secondary_disabled_surface",
    "post_focus.secondary_disabled_border",
    "post_focus.ghost_text",
    "post_focus.ghost_border",
    "post_focus.ghost_hover_surface",
    "post_focus.ghost_hover_text",
    "pause.hub_title_text",
    "pause.hub_subtitle_text",
    "pause.timer_panel_surface",
    "pause.timer_panel_border",
    "pause.records_panel_surface",
    "pause.records_panel_border",
    "pause.record_card_surface",
    "pause.record_card_border",
    "pause.section_title_text",
    "pause.record_title_text",
    "pause.record_value_text",
    "pause.timer_status_text",
    "pause.timer_value_surface",
    "pause.timer_value_text",
    "pause.timer_value_border",
    "pause.primary_surface",
    "pause.primary_border",
    "pause.primary_hover_surface",
    "pause.primary_hover_border",
    "pause.secondary_surface",
    "pause.secondary_text",
    "pause.secondary_border",
    "pause.secondary_hover_surface",
    "pause.secondary_hover_text",
    "pause.secondary_hover_border",
    "game.hint_text",
    "game.board_surface",
    "game.board_border",
    "game.title_text",
    "game.metric_text",
    "game.status_text",
    "game.primary_surface",
    "game.primary_border",
    "game.primary_hover_surface",
    "game.primary_hover_border",
    "game.cell_surface",
    "game.cell_text",
    "game.cell_border",
    "game.chimp_number_surface",
    "game.chimp_number_text",
    "game.chimp_number_border",
    "game.chimp_correct_surface",
    "game.chimp_correct_text",
    "game.chimp_correct_border",
    "game.memory_hidden_surface",
    "game.memory_hidden_text",
    "game.memory_hidden_border",
    "game.memory_open_surface",
    "game.memory_open_text",
    "game.memory_open_border",
    "game.memory_matched_surface",
    "game.memory_matched_text",
    "game.memory_matched_border",
    "game.sequence_surface",
    "game.sequence_border",
    "game.sequence_lit_surface",
    "game.sequence_lit_border",
    "game.puzzle_movable_surface",
    "game.puzzle_movable_text",
    "game.puzzle_movable_border",
    "game.puzzle_blank_surface",
    "game.puzzle_blank_border",
    "game.puzzle_blank_text",
    "game.rotation_correct_surface",
    "game.rotation_correct_border",
    "game.rotation_wrong_surface",
    "game.rotation_wrong_border",
    "dashboard.canvas",
    "dashboard.title_text",
    "dashboard.subtitle_text",
    "dashboard.topbar_surface",
    "dashboard.topbar_border",
    "dashboard.profile_bar_surface",
    "dashboard.profile_bar_border",
    "dashboard.profile_label_text",
    "dashboard.profile_input_surface",
    "dashboard.profile_input_text",
    "dashboard.profile_input_border",
    "dashboard.profile_input_hover_surface",
    "dashboard.profile_input_hover_border",
    "dashboard.search_surface",
    "dashboard.search_text",
    "dashboard.search_border",
    "dashboard.search_hover_surface",
    "dashboard.search_hover_text",
    "dashboard.search_hover_border",
    "dashboard.nav_surface",
    "dashboard.nav_text",
    "dashboard.nav_border",
    "dashboard.nav_hover_surface",
    "dashboard.nav_hover_text",
    "dashboard.nav_hover_border",
    "dashboard.nav_pressed_surface",
    "dashboard.nav_pressed_border",
    "dashboard.secondary_surface",
    "dashboard.secondary_text",
    "dashboard.secondary_border",
    "dashboard.secondary_hover_surface",
    "dashboard.secondary_hover_text",
    "dashboard.secondary_hover_border",
    "dashboard.accent_surface",
    "dashboard.accent_border",
    "dashboard.accent_hover_surface",
    "dashboard.accent_hover_border",
    "dashboard.accent_pressed_surface",
    "dashboard.focus_panel_surface",
    "dashboard.focus_panel_border",
    "dashboard.focus_card_border",
    "dashboard.focus_icon_text",
    "dashboard.focus_icon_surface",
    "dashboard.focus_icon_border",
    "dashboard.focus_title_text",
    "dashboard.focus_badge_text",
    "dashboard.focus_badge_surface",
    "dashboard.focus_badge_border",
    "dashboard.focus_description_text",
    "dashboard.focus_detail_text",
    "dashboard.focus_caption_text",
    "dashboard.focus_value_text",
    "dashboard.focus_goal_surface",
    "dashboard.focus_goal_border",
    "dashboard.focus_goal_title_text",
    "dashboard.focus_progress_track",
    "dashboard.focus_progress_border",
    "dashboard.focus_progress_fill",
    "dashboard.focus_action_text",
    "dashboard.focus_action_border",
    "dashboard.focus_action_hover_border",
    "dashboard.focus_action_pressed_surface",
    "dashboard.focus_action_pressed_border",
    "dashboard.planning_card_border",
    "dashboard.planning_icon_text",
    "dashboard.planning_icon_surface",
    "dashboard.planning_icon_border",
    "dashboard.planning_title_text",
    "dashboard.planning_date_text",
    "dashboard.planning_hero_title_text",
    "dashboard.planning_hero_value_text",
    "dashboard.planning_hero_detail_text",
    "dashboard.planning_progress_track",
    "dashboard.planning_operational_surface",
    "dashboard.planning_operational_border",
    "dashboard.planning_row_title_text",
    "dashboard.planning_operational_value_text",
    "dashboard.planning_row_detail_text",
    "dashboard.planning_divider",
    "dashboard.planning_week_label_text",
    "dashboard.planning_status_surface",
    "dashboard.planning_status_text",
    "dashboard.planning_status_border",
    "dashboard.planning_status_done_surface",
    "dashboard.planning_status_done_text",
    "dashboard.planning_status_done_border",
    "dashboard.planning_status_attention_surface",
    "dashboard.planning_status_attention_text",
    "dashboard.planning_status_attention_border",
    "dashboard.planning_status_active_surface",
    "dashboard.planning_status_active_text",
    "dashboard.planning_status_active_border",
    "dashboard.planning_button_surface",
    "dashboard.planning_button_text",
    "dashboard.planning_button_border",
    "dashboard.planning_button_hover_surface",
    "dashboard.planning_button_hover_text",
    "dashboard.planning_button_hover_border",
    "dashboard.recommendation_card_border",
    "dashboard.recommendation_icon_text",
    "dashboard.recommendation_icon_border",
    "dashboard.recommendation_title_text",
    "dashboard.recommendation_subtitle_text",
    "dashboard.recommendation_help_surface",
    "dashboard.recommendation_help_text",
    "dashboard.recommendation_help_border",
    "dashboard.recommendation_help_hover_surface",
    "dashboard.recommendation_help_hover_text",
    "dashboard.recommendation_help_hover_border",
    "dashboard.recommendation_body_surface",
    "dashboard.recommendation_body_border",
    "dashboard.recommendation_ready_text",
    "dashboard.recommendation_primary_text",
    "dashboard.recommendation_primary_border",
    "dashboard.recommendation_primary_hover_border",
    "dashboard.recommendation_primary_pressed_surface",
    "dashboard.recommendation_primary_pressed_border",
    "dashboard.recommendation_secondary_text",
    "dashboard.recommendation_secondary_hover_text",
    "dashboard.progress_card_border",
    "dashboard.progress_icon_text",
    "dashboard.progress_icon_surface",
    "dashboard.progress_icon_border",
    "dashboard.progress_title_text",
    "dashboard.progress_description_text",
    "dashboard.progress_detail_text",
    "dashboard.progress_badge_surface",
    "dashboard.progress_badge_text",
    "dashboard.progress_badge_border",
    "dashboard.progress_track",
    "dashboard.progress_button_surface",
    "dashboard.progress_button_text",
    "dashboard.progress_button_border",
    "dashboard.progress_button_hover_surface",
    "dashboard.progress_button_hover_text",
    "dashboard.progress_button_hover_border",
    "dashboard.quick_border",
    "dashboard.quick_toggle_text",
    "dashboard.quick_toolbar_text",
    "dashboard.quick_toolbar_border",
    "dashboard.quick_toolbar_hover_text",
    "dashboard.quick_toolbar_hover_border",
    "dashboard.quick_pause_text",
    "dashboard.quick_pause_border",
    "dashboard.quick_pause_hover_text",
    "dashboard.quick_pause_hover_border",
    "dashboard.overview_card_border",
    "dashboard.overview_title_text",
    "dashboard.overview_info_text",
    "dashboard.overview_divider",
    "dashboard.overview_vertical_divider",
    "dashboard.rhythm_main_text",
    "dashboard.rhythm_caption_text",
    "dashboard.rhythm_line_label_text",
    "dashboard.rhythm_today_dot_text",
    "dashboard.rhythm_late_dot_text",
    "dashboard.rhythm_today_value_text",
    "dashboard.rhythm_late_value_text",
    "dashboard.rhythm_status_ok_text",
    "dashboard.rhythm_status_attention_text",
    "dashboard.rhythm_summary_text",
    "dashboard.quality_eyebrow_text",
    "dashboard.quality_caption_text",
    "dashboard.quality_trend_surface",
    "dashboard.quality_trend_border",
    "dashboard.quality_trend_text",
    "dashboard.quality_trend_positive_text",
    "dashboard.quality_trend_negative_text",
    "dashboard.quality_trend_stable_text",
    "dashboard.quality_trend_label_text",
    "dashboard.quality_footer_text",
    "dashboard.projection_title_text",
    "dashboard.projection_caption_text",
    "dashboard.projection_detail_text",
    "dashboard.projection_percent_text",
    "dashboard.projection_bar_track",
    "dashboard.projection_bar_border",
    "dashboard.projection_bar_fill",
    "dashboard.projection_metric_surface",
    "dashboard.projection_metric_border",
    "dashboard.projection_metric_label_text",
    "dashboard.projection_metric_value_text",
    "dashboard.projection_metric_consolidating_text",
    "dashboard.projection_metric_consolidated_text",
    "dashboard.projection_metric_domain_text",
    "dashboard.projection_action_text",
    "dashboard.projection_action_border",
    "dashboard.projection_action_hover_border",
    "dashboard.notifications_panel_surface",
    "dashboard.notifications_panel_border",
    "dashboard.notifications_toggle_text",
    "dashboard.notifications_toggle_hover_surface",
    "dashboard.notifications_subtitle_text",
    "dashboard.attention_priority_surface",
    "dashboard.attention_priority_border",
    "dashboard.attention_priority_ok_surface",
    "dashboard.attention_priority_ok_border",
    "dashboard.attention_priority_critical_surface",
    "dashboard.attention_priority_critical_border",
    "dashboard.attention_priority_icon_surface",
    "dashboard.attention_priority_icon_text",
    "dashboard.attention_priority_icon_border",
    "dashboard.attention_priority_icon_ok_surface",
    "dashboard.attention_priority_icon_ok_text",
    "dashboard.attention_priority_icon_ok_border",
    "dashboard.attention_priority_icon_critical_surface",
    "dashboard.attention_priority_icon_critical_text",
    "dashboard.attention_priority_icon_critical_border",
    "dashboard.attention_eyebrow_text",
    "dashboard.attention_title_text",
    "dashboard.attention_description_text",
    "dashboard.attention_meta_text",
    "dashboard.attention_badge_surface",
    "dashboard.attention_badge_text",
    "dashboard.attention_badge_border",
    "dashboard.attention_badge_ok_surface",
    "dashboard.attention_badge_ok_text",
    "dashboard.attention_badge_ok_border",
    "dashboard.attention_badge_critical_surface",
    "dashboard.attention_badge_critical_text",
    "dashboard.attention_badge_critical_border",
    "dashboard.attention_action_surface",
    "dashboard.attention_action_text",
    "dashboard.attention_action_border",
    "dashboard.attention_action_hover_surface",
    "dashboard.attention_action_hover_text",
    "dashboard.attention_action_hover_border",
    "dashboard.attention_action_disabled_surface",
    "dashboard.attention_action_disabled_text",
    "dashboard.attention_action_disabled_border",
    "dashboard.attention_pace_surface",
    "dashboard.attention_pace_border",
    "dashboard.attention_pace_icon_surface",
    "dashboard.attention_pace_icon_text",
    "dashboard.attention_pace_icon_border",
    "dashboard.attention_pace_badge_surface",
    "dashboard.attention_pace_badge_text",
    "dashboard.attention_pace_badge_border",
    "dashboard.attention_forecast_action_surface",
    "dashboard.attention_forecast_action_text",
    "dashboard.attention_forecast_action_border",
    "dashboard.attention_forecast_action_hover_surface",
    "dashboard.attention_forecast_action_hover_text",
    "dashboard.attention_forecast_action_hover_border",
    "dashboard.attention_forecast_action_disabled_border",
    "dashboard.attention_footer_surface",
    "dashboard.attention_footer_border",
    "dashboard.attention_footer_item_text",
    "dashboard.attention_footer_hint_text",
    "dashboard.planning_full_panel_surface",
    "dashboard.planning_full_panel_border",
    "dashboard.planning_full_toggle_text",
    "dashboard.planning_full_toggle_hover_surface",
    "dashboard.planning_full_subtitle_text",
    "dashboard.planning_full_subsection_title_text",
    "dashboard.planning_full_subsection_hint_text",
    "dashboard.planning_full_micro_label_text",
    "dashboard.planning_full_box_surface",
    "dashboard.planning_full_box_border",
    "dashboard.planning_full_item_title_text",
    "dashboard.planning_full_daily_value_text",
    "dashboard.planning_full_daily_progress_track",
    "dashboard.planning_full_daily_progress_fill",
    "dashboard.planning_full_progress_complete_fill",
    "dashboard.planning_full_hint_text",
    "dashboard.planning_full_hint_complete_text",
    "dashboard.planning_full_total_badge_surface",
    "dashboard.planning_full_total_badge_text",
    "dashboard.planning_full_total_badge_border",
    "dashboard.planning_full_inset_surface",
    "dashboard.planning_full_inset_border",
    "dashboard.planning_full_day_today_surface",
    "dashboard.planning_full_day_today_border",
    "dashboard.planning_full_day_light_surface",
    "dashboard.planning_full_day_light_border",
    "dashboard.planning_full_day_moderate_surface",
    "dashboard.planning_full_day_moderate_border",
    "dashboard.planning_full_day_high_surface",
    "dashboard.planning_full_day_high_border",
    "dashboard.planning_full_day_name_text",
    "dashboard.planning_full_day_today_text",
    "dashboard.planning_full_day_date_text",
    "dashboard.planning_full_day_today_date_text",
    "dashboard.planning_full_day_count_text",
    "dashboard.planning_full_primary_action_text",
    "dashboard.planning_full_primary_action_border",
    "dashboard.planning_full_goal_hover_border",
    "dashboard.planning_full_journey_hover_border",
    "dashboard.planning_full_journey_paused_text",
    "dashboard.planning_full_journey_paused_border",
    "dashboard.planning_full_journey_ended_text",
    "dashboard.planning_full_journey_ended_border",
    "dashboard.planning_full_auto_hover_border",
    "dashboard.planning_full_auto_active_border",
    "dashboard.planning_full_auto_active_hover_border",
    "dashboard.planning_full_summary_text",
    "dashboard.planning_full_summary_border",
    "dashboard.planning_full_summary_hover_text",
    "dashboard.planning_full_summary_hover_border",
    "dashboard.planning_full_summary_pressed_text",
    "dashboard.planning_full_summary_pressed_border",
    "dashboard.planning_full_redistribute_text",
    "dashboard.planning_full_redistribute_border",
    "dashboard.planning_full_redistribute_hover_text",
    "dashboard.planning_full_redistribute_hover_border",
    "dashboard.planning_full_redistribute_pressed_text",
    "dashboard.planning_full_redistribute_pressed_border",
    "dashboard.planning_full_redistribute_suggest_text",
    "dashboard.planning_full_redistribute_suggest_border",
    "dashboard.planning_full_redistribute_suggest_hover_text",
    "dashboard.planning_full_redistribute_suggest_hover_border",
    "dashboard.planning_full_week_period_text",
    "dashboard.planning_full_week_status_off_surface",
    "dashboard.planning_full_week_status_off_text",
    "dashboard.planning_full_week_status_off_border",
    "dashboard.planning_full_week_status_active_surface",
    "dashboard.planning_full_week_status_active_text",
    "dashboard.planning_full_week_status_active_border",
    "dashboard.planning_full_week_status_attention_surface",
    "dashboard.planning_full_week_status_attention_text",
    "dashboard.planning_full_week_status_attention_border",
    "dashboard.planning_full_week_status_done_surface",
    "dashboard.planning_full_week_status_done_text",
    "dashboard.planning_full_week_status_done_border",
    "dashboard.planning_full_empty_border",
    "dashboard.planning_full_empty_title_text",
    "dashboard.planning_full_metric_title_text",
    "dashboard.planning_full_metric_value_text",
    "dashboard.planning_full_metric_hint_text",
    "dashboard.planning_full_metric_track",
    "dashboard.planning_full_metric_border",
    "dashboard.study_questions_panel_surface",
    "dashboard.study_questions_panel_border",
    "dashboard.study_questions_header_icon_surface",
    "dashboard.study_questions_header_icon_text",
    "dashboard.study_questions_header_icon_border",
    "dashboard.study_questions_toggle_text",
    "dashboard.study_questions_toggle_hover_surface",
    "dashboard.study_questions_subtitle_text",
    "dashboard.study_questions_foundation_text",
    "dashboard.study_questions_review_border",
    "dashboard.study_questions_adaptive_surface",
    "dashboard.study_questions_adaptive_border",
    "dashboard.study_questions_simulation_border",
    "dashboard.study_questions_recovery_border",
    "dashboard.study_questions_review_icon_surface",
    "dashboard.study_questions_review_icon_text",
    "dashboard.study_questions_review_icon_border",
    "dashboard.study_questions_strategy_icon_surface",
    "dashboard.study_questions_strategy_icon_text",
    "dashboard.study_questions_strategy_icon_border",
    "dashboard.study_questions_simulation_icon_surface",
    "dashboard.study_questions_simulation_icon_text",
    "dashboard.study_questions_simulation_icon_border",
    "dashboard.study_questions_title_text",
    "dashboard.study_questions_review_count_text",
    "dashboard.study_questions_description_text",
    "dashboard.study_questions_review_detail_text",
    "dashboard.study_questions_criteria_text",
    "dashboard.study_questions_assessment_badge_surface",
    "dashboard.study_questions_assessment_badge_text",
    "dashboard.study_questions_assessment_badge_border",
    "dashboard.study_questions_assessment_stat_surface",
    "dashboard.study_questions_assessment_stat_border",
    "dashboard.study_questions_assessment_stat_label_text",
    "dashboard.study_questions_assessment_stat_value_text",
    "dashboard.study_questions_subtle_surface",
    "dashboard.study_questions_subtle_text",
    "dashboard.study_questions_subtle_border",
    "dashboard.study_questions_subtle_hover_surface",
    "dashboard.study_questions_subtle_hover_text",
    "dashboard.study_questions_subtle_hover_border",
    "dashboard.study_questions_adaptive_action_text",
    "dashboard.study_questions_adaptive_action_border",
    "dashboard.study_questions_adaptive_action_hover_text",
    "dashboard.study_questions_adaptive_action_hover_border",
    "dashboard.study_questions_simulation_action_text",
    "dashboard.study_questions_simulation_action_border",
    "dashboard.study_questions_simulation_action_hover_text",
    "dashboard.study_questions_simulation_action_hover_border",
    "dashboard.study_questions_manual_footer_surface",
    "dashboard.study_questions_manual_footer_border",
    "dashboard.study_questions_manual_badge_surface",
    "dashboard.study_questions_manual_badge_text",
    "dashboard.study_questions_manual_badge_border",
    "dashboard.study_questions_manual_text",
    "dashboard.disciplines_header_surface",
    "dashboard.disciplines_header_border",
    "dashboard.disciplines_toggle_text",
    "dashboard.disciplines_toggle_hover_surface",
    "dashboard.disciplines_edit_surface",
    "dashboard.disciplines_edit_text",
    "dashboard.disciplines_edit_border",
    "dashboard.disciplines_edit_hover_surface",
    "dashboard.disciplines_edit_hover_text",
    "dashboard.disciplines_edit_hover_border",
    "dashboard.disciplines_edit_pressed_surface",
    "dashboard.disciplines_edit_pressed_border",
    "dashboard.disciplines_button_surface",
    "dashboard.disciplines_button_text",
    "dashboard.disciplines_button_border",
    "dashboard.disciplines_button_hover_surface",
    "dashboard.disciplines_button_hover_text",
    "dashboard.disciplines_button_hover_border",
    "dashboard.disciplines_disabled_surface",
    "dashboard.disciplines_disabled_text",
    "dashboard.disciplines_disabled_border",
    "dashboard.planning_arc_track",
    "dashboard.planning_arc_fill",
    "dashboard.planning_arc_text",
    "dashboard.quality_donut_track_dark",
    "dashboard.quality_donut_track_light",
    "dashboard.quality_donut_fill",
    "navigation.command_canvas",
    "navigation.command_title_text",
    "navigation.command_meta_text",
    "navigation.command_shortcut_surface",
    "navigation.command_shortcut_text",
    "navigation.command_shortcut_border",
    "navigation.command_input_surface",
    "navigation.command_input_text",
    "navigation.command_input_border",
    "navigation.command_input_selection",
    "navigation.command_input_focus_border",
    "navigation.command_results_surface",
    "navigation.command_results_text",
    "navigation.command_results_border",
    "navigation.command_results_selection_surface",
    "navigation.command_results_selection_text",
    "navigation.command_results_divider",
    "navigation.command_header_surface",
    "navigation.command_header_text",
    "navigation.command_header_border",
    "navigation.back_text",
    "navigation.back_border",
    "navigation.back_hover_text",
    "navigation.back_hover_border",
    # Central de Questões — faixa de inventário (piloto cromático)
    "questions_center.inventory_surface",
    "questions_center.inventory_border",
    "questions_center.inventory_value_text",
    "questions_center.inventory_label_text",
    "questions_center.inventory_divider",
    "card.dialog_surface",
    "card.dialog_border",
    "card.metric_surface",
    "card.metric_border",
    "card.mini_stat_surface",
    "card.mini_stat_border",
    "card.metric_label_text",
    "card.metric_value_text",
    "card.study_action_border",
    "card.study_action_review_border",
    "card.study_action_adaptive_border",
    "card.evolution_stat_border",
    "card.evolution_stat_label_text",
    "card.evolution_stat_value_text",
    "card.evolution_stat_detail_text",
    "system_status.canvas", "system_status.border", "system_status.surface",
    "system_status.surface_border", "system_status.text_primary", "system_status.text_status",
    "system_status.text_secondary", "system_status.text_accent", "system_status.progress_track",
    "system_status.progress_border", "system_status.progress_fill",
    "startup.logo_surface", "startup.logo_border", "startup.subtitle_text",
    "startup.footer_text", "startup.logo_fallback", "startup.progress_pulse",
    "task_indicator.mark_surface", "task_indicator.mark_border", "task_indicator.mark_text",
)

_COMPONENT_GRADIENT_PATHS = (
    "answer.selected_gradient", "answer.correct_gradient", "answer.incorrect_gradient",
    "answer.struck_gradient",
    "progress.fill_gradient", "session.overview_gradient", "session.statement_gradient",
    "session.action_panel_gradient",
    "summary.adaptive_gradient", "summary.effectiveness_gradient",
    "focus_mode.action_gradient", "focus_mode.action_hover_gradient",
    "post_focus.primary_gradient", "pause.primary_gradient", "game.primary_gradient",
    "dashboard.topbar_gradient", "dashboard.nav_gradient", "dashboard.nav_hover_gradient",
    "dashboard.focus_card_gradient", "dashboard.focus_action_gradient", "dashboard.focus_action_hover_gradient", "dashboard.planning_card_gradient", "dashboard.planning_progress_gradient",
    "dashboard.recommendation_card_gradient", "dashboard.recommendation_icon_gradient", "dashboard.recommendation_primary_gradient", "dashboard.recommendation_primary_hover_gradient", "dashboard.progress_card_gradient", "dashboard.progress_fill_gradient", "dashboard.quick_access_gradient", "dashboard.quick_toolbar_gradient", "dashboard.quick_toolbar_hover_gradient", "dashboard.quick_pause_gradient", "dashboard.quick_pause_hover_gradient",
    "dashboard.overview_card_gradient", "dashboard.projection_action_gradient", "dashboard.projection_action_hover_gradient",
    "dashboard.planning_full_primary_action_gradient",
    "dashboard.planning_full_primary_action_hover_gradient",
    "dashboard.planning_full_journey_hover_gradient",
    "dashboard.planning_full_journey_paused_gradient",
    "dashboard.planning_full_journey_ended_gradient",
    "dashboard.planning_full_auto_active_gradient",
    "dashboard.planning_full_auto_active_hover_gradient",
    "dashboard.planning_full_summary_gradient",
    "dashboard.planning_full_summary_hover_gradient",
    "dashboard.planning_full_summary_pressed_gradient",
    "dashboard.planning_full_redistribute_gradient",
    "dashboard.planning_full_redistribute_hover_gradient",
    "dashboard.planning_full_redistribute_pressed_gradient",
    "dashboard.planning_full_redistribute_suggest_gradient",
    "dashboard.planning_full_redistribute_suggest_hover_gradient",
    "dashboard.planning_full_metric_progress_gradient",
    "dashboard.planning_full_metric_progress_complete_gradient",
    "dashboard.study_questions_base_card_gradient",
    "dashboard.study_questions_simulation_card_gradient",
    "dashboard.study_questions_adaptive_action_gradient",
    "dashboard.study_questions_adaptive_action_hover_gradient",
    "dashboard.study_questions_simulation_action_gradient",
    "dashboard.study_questions_simulation_action_hover_gradient",
    "navigation.back_surface_gradient", "navigation.back_hover_surface_gradient",
    "card.study_action_surface_gradient", "card.study_action_adaptive_surface_gradient",
    "card.evolution_stat_surface_gradient",
    "startup.progress_gradient", "startup.shimmer_gradient",
)

FIXED_TOKEN_PATHS = frozenset(
    path
    for path in (*_COMPONENT_COLOR_PATHS, *_COMPONENT_GRADIENT_PATHS)
    if path.startswith(("system_status.", "startup.", "task_indicator."))
)


def _specs(paths: tuple[str, ...], level: TokenLevel, kind: TokenKind) -> tuple[TokenSpec, ...]:
    return tuple(TokenSpec(path, level, kind) for path in paths)


SEMANTIC_TOKENS = (
    *_specs(_SEMANTIC_COLOR_PATHS, TokenLevel.SEMANTIC, TokenKind.COLOR),
    *_specs(_SEMANTIC_GRADIENT_PATHS, TokenLevel.SEMANTIC, TokenKind.GRADIENT),
)
COMPONENT_TOKENS = (
    *_specs(_COMPONENT_COLOR_PATHS, TokenLevel.COMPONENT, TokenKind.COLOR),
    *_specs(_COMPONENT_GRADIENT_PATHS, TokenLevel.COMPONENT, TokenKind.GRADIENT),
)
ALL_TOKENS = (*SEMANTIC_TOKENS, *COMPONENT_TOKENS)

_TOKEN_INDEX: Mapping[str, TokenSpec] = MappingProxyType({token.path: token for token in ALL_TOKENS})
if len(_TOKEN_INDEX) != len(ALL_TOKENS):
    raise RuntimeError("O contrato contém caminhos de token duplicados.")


def token_spec(path: str) -> TokenSpec:
    try:
        return _TOKEN_INDEX[path]
    except KeyError as exc:
        raise KeyError(f"Token inexistente no contrato: {path!r}") from exc


def iter_tokens(
    *, level: TokenLevel | None = None, kind: TokenKind | None = None
) -> Iterator[TokenSpec]:
    return (
        token
        for token in ALL_TOKENS
        if (level is None or token.level is level) and (kind is None or token.kind is kind)
    )


SEMANTIC_TOKEN_COUNT = len(SEMANTIC_TOKENS)
COMPONENT_TOKEN_COUNT = len(COMPONENT_TOKENS)
