"""Contrato público de tokens do Design System."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from types import MappingProxyType
from typing import Iterator, Mapping


class TokenLevel(str, Enum):
    SEMANTIC = "semantic"
    COMPONENT = "component"


class TokenKind(str, Enum):
    COLOR = "color"
    GRADIENT = "gradient"


class VisualState(str, Enum):
    NORMAL = "normal"
    HOVER = "hover"
    PRESSED = "pressed"
    SELECTED = "selected"
    FOCUSED = "focused"
    KEYBOARD_FOCUS = "keyboard_focus"
    CHECKED = "checked"
    DISABLED = "disabled"
    CORRECT = "correct"
    INCORRECT = "incorrect"
    STRUCK = "struck"


@dataclass(frozen=True, slots=True)
class TokenSpec:
    path: str
    level: TokenLevel
    kind: TokenKind = TokenKind.COLOR

    def __post_init__(self) -> None:
        parts = self.path.split(".")
        if len(parts) < 2 or any(not part or not part.isidentifier() for part in parts):
            raise ValueError(f"Caminho de token inválido: {self.path!r}")


_SEMANTIC_COLOR_PATHS = (
    "canvas.app", "canvas.dialog", "canvas.inset",
    "surface.primary", "surface.secondary", "surface.tertiary", "surface.elevated",
    "surface.inset", "surface.hover", "surface.pressed", "surface.selected", "surface.disabled",
    "surface.interactive", "surface.inverse", "surface.focused",
    "text.primary", "text.secondary", "text.muted", "text.disabled", "text.inverse",
    "text.link", "text.on_action", "text.on_feedback", "text.control", "text.selected",
    "text.choice", "text.header", "text.interactive_hover", "text.selection_accent",
    "text.control_subtle", "text.readonly", "text.popup",
    "border.default", "border.subtle", "border.strong", "border.hover", "border.active",
    "border.selected", "border.disabled", "border.focus", "border.control_subtle", "border.control_hover",
    "border.divider", "border.divider_strong", "border.grid", "border.control_indicator", "border.checked",
    "action.primary", "action.primary_hover", "action.primary_pressed", "action.primary_disabled",
    "action.secondary", "action.secondary_hover", "action.secondary_pressed", "action.secondary_disabled",
    "action.ghost", "action.ghost_hover", "action.checked", "action.destructive", "action.destructive_hover",
    "feedback.success_surface", "feedback.success_text", "feedback.success_border", "feedback.success_icon",
    "feedback.warning_surface", "feedback.warning_text", "feedback.warning_border", "feedback.warning_icon",
    "feedback.danger_surface", "feedback.danger_text", "feedback.danger_border", "feedback.danger_icon",
    "feedback.info_surface", "feedback.info_text", "feedback.info_border", "feedback.info_icon",
    "focus.ring", "focus.keyboard",
    "icon.default", "icon.muted", "icon.disabled", "icon.action", "icon.highlight", "icon.configuration",
    "overlay.scrim", "overlay.light", "overlay.dark", "overlay.selection", "overlay.selection_subtle",
    "glow.primary", "glow.focus", "glow.success", "glow.danger",
)

_SEMANTIC_GRADIENT_PATHS = (
    "gradient.action_primary", "gradient.action_primary_hover", "gradient.surface_elevated",
    "gradient.hero", "gradient.progress", "gradient.control_input",
    "gradient.control_header", "gradient.control_tab", "gradient.control_selected",
)

_COMPONENT_COLOR_PATHS = (
    # Modais — Sessão A — Cartões de configuração e resumo da sessão — estrutura
    "session_modal.cards_surface",
    "session_modal.cards_border",

    # Modais — Sessão B — Progresso da sessão — texto, trilho e preenchimento
    "session_modal.progress_text",
    "session_modal.progress_track",
    "session_modal.progress_fill",

    # Modais — Sessão C — Minicartão de estatísticas da sessão — estrutura
    "session_modal.mini_stat_surface",
    "session_modal.mini_stat_border",

    # Estudo — Sessão A — Cartões da fila e sessão atual — fundo e borda
    "study_session.queue_card_surface",
    "study_session.queue_card_border",
    "study_session.current_card_surface",
    "study_session.current_card_border",

    # Estudo — Sessão B — Rótulos da fila e da sessão — seis textos
    "study_session.eyebrow_text",
    "study_session.position_text",
    "study_session.discipline_text",
    "study_session.topic_text",
    "study_session.detail_value_text",
    "study_session.section_title_text",

    # Planejamento — Rótulos de Seções do Planejamento
    "planning.section_subtitle_text",
    "planning.subsection_title_text",

    # Planejamento — Estrutura dos Cartões de Metas
    "planning.goal_card_surface",
    "planning.goal_card_border",

    # Planejamento — Títulos dos Cartões de Metas
    "planning.goal_card_title_text",

    # Planejamento — Cartão de Carga Diária — Estrutura
    "planning.weekday_card_surface",
    "planning.weekday_card_border",

    # Planejamento — Cartão de Hoje — Destaque
    "planning.weekday_today_surface",
    "planning.weekday_today_border",

    # Planejamento — Carga por Dia — Estados Leve, Moderada e Alta
    "planning.weekday_light_surface",
    "planning.weekday_light_border",
    "planning.weekday_moderate_surface",
    "planning.weekday_moderate_border",
    "planning.weekday_high_surface",
    "planning.weekday_high_border",

    # Planejamento — Carga por Dia — Nome, Data, Contagem e Destaque de Hoje
    "planning.weekday_name_text",
    "planning.weekday_date_text",
    "planning.weekday_count_text",
    "planning.weekday_today_label_text",

    # Planejamento — Painel Reorganizado — Fundo e Borda
    "planning.reorganized_panel_surface",
    "planning.reorganized_panel_border",

    # Planejamento — Subseções — Textos Auxiliares
    "planning.subsection_hint_text",
    "planning.micro_label_text",

    # Planejamento A — migração cromática
    "planning.panel_surface",
    "planning.panel_border",

    # Planejamento B — migração cromática
    "planning.settings_surface",
    "planning.settings_border",
    "planning.settings_title",
    "planning.load_light",
    "planning.load_moderate",
    "planning.load_high",
    "planning.main_title",

    # Planejamento C — migração cromática
    "planning.goal_surface",
    "planning.goal_text",
    "planning.goal_border",

    # Planejamento: PLANEJAMENTO_RESUMO_BOTAO_BASE_V1
    "planning.summary_button_surface",
    "planning.summary_button_text",
    "planning.summary_button_border",

    # Planejamento: PLANEJAMENTO_RESUMO_BOTAO_HOVER_V1
    "planning.summary_button_hover_surface",
    "planning.summary_button_hover_border",
    "planning.summary_button_hover_text",

    # Planejamento: PLANEJAMENTO_REDISTRIBUIR_BOTAO_BASE_V1
    "planning.redistribute_button_surface",
    "planning.redistribute_button_text",
    "planning.redistribute_button_border",

    # Planejamento: PLANEJAMENTO_REDISTRIBUIR_BOTAO_HOVER_V1
    "planning.redistribute_button_hover_surface",
    "planning.redistribute_button_hover_border",
    "planning.redistribute_button_hover_text",

    # Planejamento — Estado vazio da meta: estrutura
    "planning.weekly_empty_surface",
    "planning.weekly_empty_border",

    # Planejamento — Estado vazio da meta: textos
    "planning.weekly_empty_title_text",
    "planning.weekly_empty_description_text",
    "planning.weekly_period_text",

    # Planejamento — Indicador de meta: estrutura
    "planning.weekly_metric_surface",
    "planning.weekly_metric_border",

    # Planejamento — Indicador de meta: textos
    "planning.weekly_metric_title_text",
    "planning.weekly_metric_value_text",
    "planning.weekly_metric_hint_text",

    # Planejamento — Barra da meta semanal: trilho e preenchimento
    "planning.weekly_progress_track",
    "planning.weekly_progress_fill",

    # Planejamento — Meta semanal concluída: barra e mensagem
    "planning.weekly_progress_completed_fill",
    "planning.weekly_completed_hint_text",

    # Planejamento — Botão de configuração da meta semanal: estado normal
    "planning.weekly_setup_button_surface",
    "planning.weekly_setup_button_text",
    "planning.weekly_setup_button_border",

    # Planejamento — Meta diária: barra de progresso
    "planning.daily_progress_track",
    "planning.daily_progress_fill",

    # Planejamento — Meta diária: valor e texto auxiliar
    "planning.daily_goal_value_text",
    "planning.daily_goal_hint_text",

    # Planejamento — Planejamento: indicador de total
    "planning.total_badge_surface",
    "planning.total_badge_text",
    "planning.total_badge_border",

    # Planejamento: PLANEJAMENTO_STATUS_SEMANAL_BASE_V1
    "planning.weekly_status_surface",
    "planning.weekly_status_text",
    "planning.weekly_status_border",

    # Planejamento: PLANEJAMENTO_STATUS_SEMANAL_CONCLUIDA_V1
    "planning.weekly_status_completed_surface",
    "planning.weekly_status_completed_text",
    "planning.weekly_status_completed_border",

    # Planejamento: PLANEJAMENTO_STATUS_SEMANAL_ATENCAO_V1
    "planning.weekly_status_attention_surface",
    "planning.weekly_status_attention_text",
    "planning.weekly_status_attention_border",

    # Planejamento D — migração cromática
    "planning.goal_hover_surface",
    "planning.goal_hover_border",
    "planning.goal_hover_text",

    # Estudo — Botões A — Botão Pausar — estados normal e hover
    "study_session.pause_button_surface",
    "study_session.pause_button_text",
    "study_session.pause_button_border",
    "study_session.pause_button_hover_surface",
    "study_session.pause_button_hover_emphasis",

    # Estudo — Botões B — Botão Encerrar — estados normal e hover
    "study_session.end_button_surface",
    "study_session.end_button_text",
    "study_session.end_button_border",
    "study_session.end_button_hover_surface",
    "study_session.end_button_hover_emphasis",

    # Estudo — Botões C — Botão Pular — estados normal e hover
    "study_session.skip_button_surface",
    "study_session.skip_button_text",
    "study_session.skip_button_border",
    "study_session.skip_button_hover_surface",
    "study_session.skip_button_hover_emphasis",

    # Estudo — Sessão C — Tabela da fila de estudos — fundo e borda
    "study_session.table_surface",
    "study_session.table_border",

    # Modais — Sessão D — Minicartão de estatísticas da sessão — rótulo e valor
    "session_modal.mini_stat_label",
    "session_modal.mini_stat_value",

    # Modais — Botão Simulados da Central de Questões — Base V1
    "mock_exam.questions_button_surface",
    "mock_exam.questions_button_text",
    "mock_exam.questions_button_border",

    # Modais — Botão Simulados da Central de Questões — Hover V1
    "mock_exam.questions_button_hover_surface",
    "mock_exam.questions_button_hover_border",

    # Modais — Botões de Iniciar e Dashboard dos Simulados — Base V1
    "mock_exam.primary_button_surface",
    "mock_exam.primary_button_text",
    "mock_exam.primary_button_border",

    # Modais — Botões de Iniciar e Dashboard dos Simulados — Hover V1
    "mock_exam.primary_button_hover_surface",
    "mock_exam.primary_button_hover_border",

    # Modais — Título dos Resultados dos Simulados V1
    "mock_exam.result_section_title_text",

    # Modais — Aviso de Correção dos Simulados V1
    "mock_exam.correction_notice_surface",
    "mock_exam.correction_notice_text",
    "mock_exam.correction_notice_border",

    # Modais — Aviso de Regras dos Simulados V1
    "mock_exam.rule_notice_surface",
    "mock_exam.rule_notice_text",
    "mock_exam.rule_notice_border",

    # Modais — Rótulos do Cartão de Configuração de Simulados V1
    "mock_exam.config_card_label_text",
    "mock_exam.section_title_text",
    "mock_exam.preview_summary_text",
    "mock_exam.explanation_text",

    # Modais — Cartão de Configuração de Simulados (Base) V1
    "mock_exam.config_card_surface",
    "mock_exam.config_card_border",

    # Modais — Botões de Acesso à Efetividade (Hover) V1
    "effectiveness.open_button_hover_surface",
    "effectiveness.open_button_hover_border",

    # Modais — Botões de Acesso à Efetividade (Base) V1
    "effectiveness.open_button_surface",
    "effectiveness.open_button_text",
    "effectiveness.open_button_border",

    # Modais — Textos das Métricas de Impacto da Efetividade V1
    "effectiveness.impact_metric_label_text",
    "effectiveness.impact_metric_value_text",
    "effectiveness.impact_metric_footer_text",

    # Modais — Minicartão de Métricas de Impacto da Efetividade V1
    "effectiveness.impact_metric_surface",
    "effectiveness.impact_metric_border",

    # Modais — Título do Cartão de Impacto da Efetividade V1
    "effectiveness.impact_title_text",

    # Modais — Cartão de Impacto da Efetividade V1
    "effectiveness.impact_card_surface",
    "effectiveness.impact_card_border",

    # Modais — Aviso de Acompanhamento da Efetividade V1
    "effectiveness.tracking_notice_text",

    # Modais — Barra de Filtros da Efetividade V1
    "effectiveness.filter_bar_surface",
    "effectiveness.filter_bar_border",
    "effectiveness.filter_bar_label_text",

    # Modais — Selo de Calibração: Nível Forte V1
    "effectiveness.calibration_badge_strong_surface",
    "effectiveness.calibration_badge_strong_text",
    "effectiveness.calibration_badge_strong_border",

    # Modais — Selo de Calibração: Níveis Inicial/Moderada V1
    "effectiveness.calibration_badge_caution_surface",
    "effectiveness.calibration_badge_caution_text",
    "effectiveness.calibration_badge_caution_border",

    # Modais — Selo de Calibração: Texto Base V1
    "effectiveness.calibration_badge_text",

    # Modais — Selo de Calibração: Fundo e Borda Base V1
    "effectiveness.calibration_badge_surface",
    "effectiveness.calibration_badge_border",

    # Modais — Metadados da Calibração V1
    "effectiveness.calibration_weights_text",
    "effectiveness.calibration_observations_text",

    # Modais — Texto Descritivo da Calibração V1
    "effectiveness.calibration_body_text",

    # Modais — Título da Calibração de Efetividade V1
    "effectiveness.calibration_title_text",

    # Modais — Cartão de Calibração de Efetividade V1
    "effectiveness.calibration_card_surface",
    "effectiveness.calibration_card_border",

    # Modais — Texto auxiliar das estatísticas de efetividade V1
    "effectiveness.stat_hint_text",

    # Modais — Detalhes em Somente Leitura V1
    "modal_details.readonly_surface",
    "modal_details.readonly_border",

    # Modais — Avisos Informativos Compartilhados V1
    "modal_notice.info_surface",
    "modal_notice.info_text",
    "modal_notice.info_border",

    # Modais — Rótulos de campos da Revisão Manual V1
    "modal_revision.field_label_text",

    # Modais — Sugestão de agendamento da Revisão Manual V1
    "modal_revision.suggestion_surface",
    "modal_revision.suggestion_border",
    "modal_revision.suggestion_text",

    # Modais — Resultado percentual da Revisão Manual V1
    "modal_revision.result_surface",
    "modal_revision.result_text",
    "modal_revision.result_border",

    # Modais — Selo de Revisão Manual V1
    "modal_revision.badge_surface",
    "modal_revision.badge_text",
    "modal_revision.badge_border",

    # Modais — Disponibilidade da Sessão V1
    "modal_session_availability.default_surface",
    "modal_session_availability.default_text",
    "modal_session_availability.default_border",
    "modal_session_availability.available_surface",
    "modal_session_availability.available_text",
    "modal_session_availability.available_border",
    "modal_session_availability.empty_surface",
    "modal_session_availability.empty_text",
    "modal_session_availability.empty_border",

    # Modais — Barra de Foco do Resolvedor V1
    "session.focus_bar_surface",
    "session.focus_bar_border",
    "session.focus_state_text",

    # Modais — Ações compactas V1 (linha e edição)
    "modal_compact_actions.row_text",
    "modal_compact_actions.row_border",
    "modal_compact_actions.row_hover_surface",
    "modal_compact_actions.row_hover_border",
    "modal_compact_actions.edit_surface",
    "modal_compact_actions.edit_text",
    "modal_compact_actions.edit_border",
    "modal_compact_actions.edit_hover_surface",
    "modal_compact_actions.edit_hover_border",
    "modal_compact_actions.edit_hover_text",
    "modal_compact_actions.edit_pressed_surface",
    "modal_compact_actions.edit_pressed_border",

    # Modais — Cartões de Início e Resumo da Sessão V1
    "modal_session_cards.card_border",
    "modal_session_cards.card_surface",
    "modal_session_cards.objective_border",
    "modal_session_cards.objective_surface",
    "modal_session_cards.objective_text",
    "modal_session_cards.table_border",
    "modal_session_cards.table_surface",

    # Modais — Resumo Diário V1
    "modal_daily.compare_average_text",
    "modal_daily.compare_border",
    "modal_daily.compare_surface",
    "modal_daily.compare_value_text",
    "modal_daily.goal_value_text",
    "modal_daily.hint_completed_text",
    "modal_daily.hint_text",
    "modal_daily.panel_border",
    "modal_daily.panel_surface",
    "modal_daily.progress_completed_surface",
    "modal_daily.progress_fill_surface",
    "modal_daily.progress_track_surface",
    "modal_daily.section_title_text",
    "modal_daily.table_border",
    "modal_daily.table_surface",
    "modal_daily.trend_negative_text",
    "modal_daily.trend_positive_text",
    "modal_daily.trend_text",

    # Modais — Cartões de Estudo e Domínio Legados V1
    "modal_study.dialog_card_border",
    "modal_study.dialog_card_surface",
    "modal_study.domain_bar_chunk_surface",
    "modal_study.domain_bar_surface",
    "modal_study.domain_card_border",
    "modal_study.domain_card_surface",
    "modal_study.domain_component_border",
    "modal_study.domain_component_label_text",
    "modal_study.domain_component_surface",
    "modal_study.domain_component_value_text",
    "modal_study.domain_evidence_text",
    "modal_study.domain_level_critico_surface",
    "modal_study.domain_level_critico_text",
    "modal_study.domain_level_desenvolvimento_surface",
    "modal_study.domain_level_desenvolvimento_text",
    "modal_study.domain_level_dominado_surface",
    "modal_study.domain_level_dominado_text",
    "modal_study.domain_level_surface",
    "modal_study.domain_level_text",
    "modal_study.domain_reasons_text",
    "modal_study.domain_score_text",
    "modal_study.domain_subtitle_text",
    "modal_study.domain_title_text",

    # Modais — Detalhes do Tópico V1 (migração QSS sem redesenho)
    "modal_topic.breadcrumb_text",
    "modal_topic.compact_metric_border",
    "modal_topic.compact_metric_surface",
    "modal_topic.compact_metric_value_text",
    "modal_topic.details_tabs_selected_bottom_border",
    "modal_topic.details_tabs_selected_text",
    "modal_topic.details_tabs_text",
    "modal_topic.dialog_surface",
    "modal_topic.domain_bar_modern_chunk_surface",
    "modal_topic.domain_bar_modern_surface",
    "modal_topic.domain_card_modern_border",
    "modal_topic.domain_card_modern_surface",
    "modal_topic.domain_component_label_modern_text",
    "modal_topic.domain_component_modern_border",
    "modal_topic.domain_component_modern_surface",
    "modal_topic.domain_component_value_modern_text",
    "modal_topic.domain_evidence_modern_text",
    "modal_topic.domain_insight_attention_border",
    "modal_topic.domain_insight_attention_surface",
    "modal_topic.domain_insight_border",
    "modal_topic.domain_insight_domain_insight_text_attention_text",
    "modal_topic.domain_insight_domain_insight_text_strength_text",
    "modal_topic.domain_insight_strength_border",
    "modal_topic.domain_insight_strength_surface",
    "modal_topic.domain_insight_surface",
    "modal_topic.domain_insight_title_text",
    "modal_topic.domain_level_modern_critico_surface",
    "modal_topic.domain_level_modern_critico_text",
    "modal_topic.domain_level_modern_desenvolvimento_surface",
    "modal_topic.domain_level_modern_desenvolvimento_text",
    "modal_topic.domain_level_modern_dominado_surface",
    "modal_topic.domain_level_modern_dominado_text",
    "modal_topic.domain_level_modern_surface",
    "modal_topic.domain_level_modern_text",
    "modal_topic.domain_score_modern_text",
    "modal_topic.domain_subtitle_modern_text",
    "modal_topic.domain_title_modern_text",
    "modal_topic.evolution_empty_border",
    "modal_topic.evolution_empty_icon_text",
    "modal_topic.evolution_empty_surface",
    "modal_topic.evolution_empty_text_text",
    "modal_topic.evolution_empty_title_text",
    "modal_topic.hero_card_border",
    "modal_topic.hero_card_surface",
    "modal_topic.hero_subtitle_text",
    "modal_topic.hero_title_text",
    "modal_topic.history_table_alternate_surface",
    "modal_topic.history_table_border",
    "modal_topic.history_table_surface",
    "modal_topic.legacy_notice_border",
    "modal_topic.legacy_notice_surface",
    "modal_topic.legacy_notice_text",
    "modal_topic.metric_card_border",
    "modal_topic.metric_card_domain_border",
    "modal_topic.metric_card_domain_surface",
    "modal_topic.metric_card_metric_value_domain_text",
    "modal_topic.metric_card_surface",
    "modal_topic.metric_label_text",
    "modal_topic.metric_value_text",
    "modal_topic.next_date_text",
    "modal_topic.next_description_text",
    "modal_topic.next_eyebrow_text",
    "modal_topic.next_primary_button_border",
    "modal_topic.next_primary_button_hover_border",
    "modal_topic.next_primary_button_hover_surface",
    "modal_topic.next_primary_button_surface",
    "modal_topic.next_primary_button_text",
    "modal_topic.next_status_future_surface",
    "modal_topic.next_status_future_text",
    "modal_topic.next_status_overdue_surface",
    "modal_topic.next_status_overdue_text",
    "modal_topic.next_status_soon_surface",
    "modal_topic.next_status_soon_text",
    "modal_topic.next_status_surface",
    "modal_topic.next_status_text",
    "modal_topic.next_status_today_surface",
    "modal_topic.next_status_today_text",
    "modal_topic.next_step_card_border",
    "modal_topic.next_step_card_surface",
    "modal_topic.questions_button_border",
    "modal_topic.questions_button_hover_border",
    "modal_topic.questions_button_hover_surface",
    "modal_topic.questions_button_hover_text",
    "modal_topic.questions_button_surface",
    "modal_topic.questions_button_text",
    "modal_topic.study_button_border",
    "modal_topic.study_button_hover_border",
    "modal_topic.study_button_hover_surface",
    "modal_topic.study_button_surface",
    "modal_topic.study_button_text",

    "answer.normal_surface", "answer.normal_border", "answer.normal_text",
    "answer.hover_surface", "answer.hover_border",
    "answer.pressed_surface", "answer.pressed_border",
    "answer.selected_surface", "answer.selected_border", "answer.selected_text",
    "answer.focused_border", "answer.keyboard_focus_border", "answer.checked_indicator",
    "answer.indicator_surface", "answer.indicator_border", "answer.indicator_hover_border",
    "answer.indicator_checked_border", "answer.indicator_text",
    "answer.disabled_surface", "answer.disabled_border", "answer.disabled_text",
    "answer.correct_surface", "answer.correct_border", "answer.correct_text",
    "answer.incorrect_surface", "answer.incorrect_border", "answer.incorrect_text",
    "answer.struck_surface", "answer.struck_border", "answer.struck_text",
    "answer.struck_hover_surface", "answer.struck_hover_border",
    "answer.eliminate_text", "answer.eliminate_hover_surface", "answer.eliminate_hover_text",
    "answer.eliminate_checked_surface", "answer.eliminate_checked_text",
    "answer.eliminate_checked_border",
    "answer.explanation_surface", "answer.explanation_border",
    "answer.explanation_title_text", "answer.explanation_text",
    "answer.editor_surface", "answer.editor_border", "answer.editor_text",
    "answer.editor_selection",
    "answer.edit_action_surface", "answer.edit_action_hover_surface",
    "answer.edit_action_hover_text", "answer.edit_action_hover_border",
    "answer.save_action_surface", "answer.save_action_text", "answer.save_action_border",
    "answer.cancel_action_surface",
    "answer.primary_action_border", "answer.primary_action_hover_border",
    "feedback.queue_detail_surface", "feedback.queue_detail_text", "feedback.queue_detail_border",
    "summary.canvas", "summary.title_text", "summary.subtitle_text",
    "summary.metric_surface", "summary.metric_border",
    "summary.metric_label_text", "summary.metric_value_text",
    "summary.detail_surface", "summary.detail_text", "summary.detail_border",
    "summary.table_surface", "summary.table_border",
    "summary.review_surface", "summary.review_border",
    "summary.review_title_text", "summary.review_text",
    "summary.adaptive_surface", "summary.adaptive_border",
    "summary.adaptive_title_text", "summary.adaptive_text",
    "summary.effectiveness_surface", "summary.effectiveness_border",
    "summary.effectiveness_title_text",
    "summary.effectiveness_metric_surface", "summary.effectiveness_metric_border",
    "summary.effectiveness_metric_label_text", "summary.effectiveness_metric_value_text",
    "summary.mock_exam_section_title_text",
    "summary.mock_exam_notice_surface", "summary.mock_exam_notice_text",
    "summary.mock_exam_notice_border",
    "progress.track", "progress.border", "progress.fill", "progress.text", "progress.complete", "progress.warning",
    "progress.session_text", "progress.session_track",
    "session.title_text", "session.subtitle_text", "session.panel_surface",
    "session.overview_border", "session.eyebrow_text", "session.cycle_text",
    "session.metric_surface", "session.metric_border", "session.metric_label_text",
    "session.metric_value_text", "session.metric_success_text",
    "session.metric_danger_text", "session.metric_warning_text",
    "session.discipline_text", "session.meta_text", "session.question_index_text",
    "session.statement_surface", "session.statement_border", "session.statement_text",
    "session.navigation_surface",
    "session.navigation_text",
    "session.navigation_border",
    "session.navigation_hover_surface",
    "session.navigation_hover_text",
    "session.navigation_hover_border",
    "session.timer_surface",
    "session.timer_text",
    "session.timer_border",
    "session.action_panel_surface",
    "session.action_panel_border",
    "session.skip_surface",
    "session.skip_text",
    "session.skip_border",
    "session.skip_hover_surface",
    "session.skip_hover_text",
    "session.skip_hover_border",
    "session.end_surface",
    "session.end_text",
    "session.end_border",
    "session.end_hover_surface",
    "session.end_hover_text",
    "session.end_hover_border",
    "session.flag_indicator_surface",
    "session.doubt_text",
    "session.doubt_checked_text",
    "session.doubt_indicator_border",
    "session.doubt_indicator_hover_border",
    "session.doubt_indicator_checked_surface",
    "session.doubt_indicator_checked_border",
    "session.doubt_indicator_disabled_surface",
    "session.doubt_indicator_disabled_border",
    "session.analysis_text",
    "session.analysis_checked_text",
    "session.analysis_indicator_border",
    "session.analysis_indicator_hover_border",
    "session.analysis_indicator_checked_surface",
    "session.analysis_indicator_checked_border",
    "calendar.surface", "calendar.today_surface", "calendar.today_border", "calendar.today_text",
    "calendar.selected_surface", "calendar.selected_text", "calendar.week_predicted_surface",
    "calendar.week_predicted_border", "calendar.week_predicted_text", "calendar.weekend_text",
    "calendar.outside_month_text", "calendar.border", "calendar.text", "calendar.title_text",
    "calendar.badge_surface", "calendar.badge_text", "calendar.badge_border",
    "calendar.legend_today", "calendar.legend_late", "calendar.legend_scheduled",
    "calendar.navigation_surface", "calendar.navigation_hover_surface",
    "calendar.input_surface", "calendar.input_border",
    "calendar.late_surface", "calendar.late_text",
    "calendar.scheduled_surface", "calendar.scheduled_text",
    "calendar.forecast_toggle_surface", "calendar.forecast_toggle_text",
    "calendar.forecast_toggle_border", "calendar.forecast_toggle_hover_surface",
    "calendar.forecast_toggle_hover_text", "calendar.forecast_toggle_hover_border",
    "calendar.forecast_toggle_checked_surface", "calendar.forecast_toggle_checked_border",
    "calendar.forecast_action_text", "calendar.forecast_meta_text",
    "calendar.forecast_panel_surface", "calendar.forecast_panel_border",
    "calendar.forecast_title_text", "calendar.forecast_notice_text",
    "calendar.forecast_today_surface", "calendar.forecast_past_surface",
    "calendar.forecast_past_border", "calendar.forecast_count_surface",
    "calendar.forecast_count_text", "calendar.forecast_badge_surface",
    "calendar.forecast_badge_text", "calendar.forecast_badge_border",
    "calendar.forecast_card_surface", "calendar.forecast_card_accent",
    "calendar.forecast_review", "calendar.forecast_completed",
    "calendar.forecast_recommendation", "calendar.forecast_simulation",
    "calendar.forecast_discipline_text", "calendar.forecast_card_text",
    "calendar.forecast_open_text", "calendar.forecast_open_hover_surface",
    "calendar.forecast_open_hover_border", "calendar.forecast_empty_text",
    "chart.axis", "chart.grid", "chart.label", "chart.series_1", "chart.series_2", "chart.series_3",
    "chart.series_4", "chart.series_5", "chart.series_6", "chart.positive", "chart.negative",
    "focus_mode.canvas", "focus_mode.panel", "focus_mode.panel_active", "focus_mode.text",
    "focus_mode.timer", "focus_mode.border",
    "focus_mode.secondary_text", "focus_mode.section_text", "focus_mode.meta_text",
    "focus_mode.panel_active_border",
    "focus_mode.hero_surface", "focus_mode.hero_border",
    "focus_mode.hero_eyebrow_text", "focus_mode.hero_value_text", "focus_mode.hero_status_text",
    "focus_mode.mini_surface", "focus_mode.mini_border",
    "focus_mode.mini_label_text", "focus_mode.mini_value_text",
    "focus_mode.secondary_action_surface", "focus_mode.secondary_action_text",
    "focus_mode.secondary_action_border", "focus_mode.secondary_action_hover_surface",
    "focus_mode.secondary_action_hover_text", "focus_mode.secondary_action_hover_border",
    "focus_mode.action", "focus_mode.action_border", "focus_mode.action_hover_border",
    "focus_mode.action_pressed_border",
    "focus_mode.danger", "focus_mode.danger_text", "focus_mode.danger_border",
    "focus_mode.danger_hover_surface", "focus_mode.danger_hover_border",
    "focus_mode.progress_track", "focus_mode.progress_fill", "focus_mode.progress_border",
    "focus_mode.optional_surface", "focus_mode.optional_border",
    "focus_mode.notice_surface", "focus_mode.notice_text", "focus_mode.notice_border",
    "focus_mode.session_bar_surface", "focus_mode.session_bar_border",
    "focus_mode.session_bar_status_text",
    "focus_mode.session_bar_button_surface", "focus_mode.session_bar_button_text",
    "focus_mode.session_bar_button_border",
    "focus_mode.session_bar_button_hover_surface", "focus_mode.session_bar_button_hover_text",
    "focus_mode.session_bar_button_hover_border",
    "post_focus.dialog_title_text",
    "post_focus.dialog_subtitle_text",
    "post_focus.hero_surface",
    "post_focus.hero_border",
    "post_focus.eyebrow_text",
    "post_focus.time_text",
    "post_focus.meta_text",
    "post_focus.mini_surface",
    "post_focus.mini_border",
    "post_focus.mini_label_text",
    "post_focus.mini_value_text",
    "post_focus.content_surface",
    "post_focus.content_border",
    "post_focus.strong_text",
    "post_focus.result_surface",
    "post_focus.result_border",
    "post_focus.result_value_text",
    "post_focus.continue_surface",
    "post_focus.continue_text",
    "post_focus.continue_border",
    "post_focus.continue_hover_surface",
    "post_focus.continue_hover_border",
    "post_focus.primary_surface",
    "post_focus.primary_border",
    "post_focus.primary_hover_surface",
    "post_focus.primary_hover_border",
    "post_focus.secondary_surface",
    "post_focus.secondary_text",
    "post_focus.secondary_border",
    "post_focus.secondary_hover_surface",
    "post_focus.secondary_hover_border",
    "post_focus.secondary_disabled_text",
    "post_focus.secondary_disabled_surface",
    "post_focus.secondary_disabled_border",
    "post_focus.ghost_text",
    "post_focus.ghost_border",
    "post_focus.ghost_hover_surface",
    "post_focus.ghost_hover_text",
    "pause.hub_title_text",
    "pause.hub_subtitle_text",
    "pause.timer_panel_surface",
    "pause.timer_panel_border",
    "pause.records_panel_surface",
    "pause.records_panel_border",
    "pause.record_card_surface",
    "pause.record_card_border",
    "pause.section_title_text",
    "pause.record_title_text",
    "pause.record_value_text",
    "pause.timer_status_text",
    "pause.timer_value_surface",
    "pause.timer_value_text",
    "pause.timer_value_border",
    "pause.primary_surface",
    "pause.primary_border",
    "pause.primary_hover_surface",
    "pause.primary_hover_border",
    "pause.secondary_surface",
    "pause.secondary_text",
    "pause.secondary_border",
    "pause.secondary_hover_surface",
    "pause.secondary_hover_text",
    "pause.secondary_hover_border",
    "game.hint_text",
    "game.board_surface",
    "game.board_border",
    "game.title_text",
    "game.metric_text",
    "game.status_text",
    "game.primary_surface",
    "game.primary_border",
    "game.primary_hover_surface",
    "game.primary_hover_border",
    "game.cell_surface",
    "game.cell_text",
    "game.cell_border",
    "game.chimp_number_surface",
    "game.chimp_number_text",
    "game.chimp_number_border",
    "game.chimp_correct_surface",
    "game.chimp_correct_text",
    "game.chimp_correct_border",
    "game.memory_hidden_surface",
    "game.memory_hidden_text",
    "game.memory_hidden_border",
    "game.memory_open_surface",
    "game.memory_open_text",
    "game.memory_open_border",
    "game.memory_matched_surface",
    "game.memory_matched_text",
    "game.memory_matched_border",
    "game.sequence_surface",
    "game.sequence_border",
    "game.sequence_lit_surface",
    "game.sequence_lit_border",
    "game.puzzle_movable_surface",
    "game.puzzle_movable_text",
    "game.puzzle_movable_border",
    "game.puzzle_blank_surface",
    "game.puzzle_blank_border",
    "game.puzzle_blank_text",
    "game.rotation_correct_surface",
    "game.rotation_correct_border",
    "game.rotation_wrong_surface",
    "game.rotation_wrong_border",
    "dashboard.canvas",
    "dashboard.title_text",
    "dashboard.subtitle_text",
    "dashboard.topbar_surface",
    "dashboard.topbar_border",
    "dashboard.profile_bar_surface",
    "dashboard.profile_bar_border",
    "dashboard.profile_label_text",
    "dashboard.profile_input_surface",
    "dashboard.profile_input_text",
    "dashboard.profile_input_border",
    "dashboard.profile_input_hover_surface",
    "dashboard.profile_input_hover_border",
    "dashboard.search_surface",
    "dashboard.search_text",
    "dashboard.search_border",
    "dashboard.search_hover_surface",
    "dashboard.search_hover_text",
    "dashboard.search_hover_border",
    "dashboard.nav_surface",
    "dashboard.nav_text",
    "dashboard.nav_border",
    "dashboard.nav_hover_surface",
    "dashboard.nav_hover_text",
    "dashboard.nav_hover_border",
    "dashboard.nav_pressed_surface",
    "dashboard.nav_pressed_border",
    "dashboard.secondary_surface",
    "dashboard.secondary_text",
    "dashboard.secondary_border",
    "dashboard.secondary_hover_surface",
    "dashboard.secondary_hover_text",
    "dashboard.secondary_hover_border",
    "dashboard.accent_surface",
    "dashboard.accent_border",
    "dashboard.accent_hover_surface",
    "dashboard.accent_hover_border",
    "dashboard.accent_pressed_surface",
    "dashboard.focus_panel_surface",
    "dashboard.focus_panel_border",
    "dashboard.focus_card_border",
    "dashboard.focus_icon_text",
    "dashboard.focus_icon_surface",
    "dashboard.focus_icon_border",
    "dashboard.focus_title_text",
    "dashboard.focus_badge_text",
    "dashboard.focus_badge_surface",
    "dashboard.focus_badge_border",
    "dashboard.focus_description_text",
    "dashboard.focus_detail_text",
    "dashboard.focus_caption_text",
    "dashboard.focus_value_text",
    "dashboard.focus_goal_surface",
    "dashboard.focus_goal_border",
    "dashboard.focus_goal_title_text",
    "dashboard.focus_progress_track",
    "dashboard.focus_progress_border",
    "dashboard.focus_progress_fill",
    "dashboard.focus_action_text",
    "dashboard.focus_action_border",
    "dashboard.focus_action_hover_border",
    "dashboard.focus_action_pressed_surface",
    "dashboard.focus_action_pressed_border",
    "dashboard.planning_card_border",
    "dashboard.planning_icon_text",
    "dashboard.planning_icon_surface",
    "dashboard.planning_icon_border",
    "dashboard.planning_title_text",
    "dashboard.planning_date_text",
    "dashboard.planning_hero_title_text",
    "dashboard.planning_hero_value_text",
    "dashboard.planning_hero_detail_text",
    "dashboard.planning_progress_track",
    "dashboard.planning_operational_surface",
    "dashboard.planning_operational_border",
    "dashboard.planning_row_title_text",
    "dashboard.planning_operational_value_text",
    "dashboard.planning_row_detail_text",
    "dashboard.planning_divider",
    "dashboard.planning_week_label_text",
    "dashboard.planning_status_surface",
    "dashboard.planning_status_text",
    "dashboard.planning_status_border",
    "dashboard.planning_status_done_surface",
    "dashboard.planning_status_done_text",
    "dashboard.planning_status_done_border",
    "dashboard.planning_status_attention_surface",
    "dashboard.planning_status_attention_text",
    "dashboard.planning_status_attention_border",
    "dashboard.planning_status_active_surface",
    "dashboard.planning_status_active_text",
    "dashboard.planning_status_active_border",
    "dashboard.planning_button_surface",
    "dashboard.planning_button_text",
    "dashboard.planning_button_border",
    "dashboard.planning_button_hover_surface",
    "dashboard.planning_button_hover_text",
    "dashboard.planning_button_hover_border",
    "dashboard.recommendation_card_border",
    "dashboard.recommendation_icon_text",
    "dashboard.recommendation_icon_border",
    "dashboard.recommendation_title_text",
    "dashboard.recommendation_subtitle_text",
    "dashboard.recommendation_help_surface",
    "dashboard.recommendation_help_text",
    "dashboard.recommendation_help_border",
    "dashboard.recommendation_help_hover_surface",
    "dashboard.recommendation_help_hover_text",
    "dashboard.recommendation_help_hover_border",
    "dashboard.recommendation_body_surface",
    "dashboard.recommendation_body_border",
    "dashboard.recommendation_ready_text",
    "dashboard.recommendation_primary_text",
    "dashboard.recommendation_primary_border",
    "dashboard.recommendation_primary_hover_border",
    "dashboard.recommendation_primary_pressed_surface",
    "dashboard.recommendation_primary_pressed_border",
    "dashboard.recommendation_secondary_text",
    "dashboard.recommendation_secondary_hover_text",
    "dashboard.progress_card_border",
    "dashboard.progress_icon_text",
    "dashboard.progress_icon_surface",
    "dashboard.progress_icon_border",
    "dashboard.progress_title_text",
    "dashboard.progress_description_text",
    "dashboard.progress_detail_text",
    "dashboard.progress_badge_surface",
    "dashboard.progress_badge_text",
    "dashboard.progress_badge_border",
    "dashboard.progress_track",
    "dashboard.progress_button_surface",
    "dashboard.progress_button_text",
    "dashboard.progress_button_border",
    "dashboard.progress_button_hover_surface",
    "dashboard.progress_button_hover_text",
    "dashboard.progress_button_hover_border",
    "dashboard.quick_border",
    "dashboard.quick_toggle_text",
    "dashboard.quick_toolbar_text",
    "dashboard.quick_toolbar_border",
    "dashboard.quick_toolbar_hover_text",
    "dashboard.quick_toolbar_hover_border",
    "dashboard.quick_pause_text",
    "dashboard.quick_pause_border",
    "dashboard.quick_pause_hover_text",
    "dashboard.quick_pause_hover_border",
    "dashboard.overview_card_border",
    "dashboard.overview_title_text",
    "dashboard.overview_info_text",
    "dashboard.overview_divider",
    "dashboard.overview_vertical_divider",
    "dashboard.rhythm_main_text",
    "dashboard.rhythm_caption_text",
    "dashboard.rhythm_line_label_text",
    "dashboard.rhythm_today_dot_text",
    "dashboard.rhythm_late_dot_text",
    "dashboard.rhythm_today_value_text",
    "dashboard.rhythm_late_value_text",
    "dashboard.rhythm_status_ok_text",
    "dashboard.rhythm_status_attention_text",
    "dashboard.rhythm_summary_text",
    "dashboard.quality_eyebrow_text",
    "dashboard.quality_caption_text",
    "dashboard.quality_trend_surface",
    "dashboard.quality_trend_border",
    "dashboard.quality_trend_text",
    "dashboard.quality_trend_positive_text",
    "dashboard.quality_trend_negative_text",
    "dashboard.quality_trend_stable_text",
    "dashboard.quality_trend_label_text",
    "dashboard.quality_footer_text",
    "dashboard.projection_title_text",
    "dashboard.projection_caption_text",
    "dashboard.projection_detail_text",
    "dashboard.projection_percent_text",
    "dashboard.projection_bar_track",
    "dashboard.projection_bar_border",
    "dashboard.projection_bar_fill",
    "dashboard.projection_metric_surface",
    "dashboard.projection_metric_border",
    "dashboard.projection_metric_label_text",
    "dashboard.projection_metric_value_text",
    "dashboard.projection_metric_consolidating_text",
    "dashboard.projection_metric_consolidated_text",
    "dashboard.projection_metric_domain_text",
    "dashboard.projection_action_text",
    "dashboard.projection_action_border",
    "dashboard.projection_action_hover_border",
    "dashboard.notifications_panel_surface",
    "dashboard.notifications_panel_border",
    "dashboard.notifications_toggle_text",
    "dashboard.notifications_toggle_hover_surface",
    "dashboard.notifications_subtitle_text",
    "dashboard.attention_priority_surface",
    "dashboard.attention_priority_border",
    "dashboard.attention_priority_ok_surface",
    "dashboard.attention_priority_ok_border",
    "dashboard.attention_priority_critical_surface",
    "dashboard.attention_priority_critical_border",
    "dashboard.attention_priority_icon_surface",
    "dashboard.attention_priority_icon_text",
    "dashboard.attention_priority_icon_border",
    "dashboard.attention_priority_icon_ok_surface",
    "dashboard.attention_priority_icon_ok_text",
    "dashboard.attention_priority_icon_ok_border",
    "dashboard.attention_priority_icon_critical_surface",
    "dashboard.attention_priority_icon_critical_text",
    "dashboard.attention_priority_icon_critical_border",
    "dashboard.attention_eyebrow_text",
    "dashboard.attention_title_text",
    "dashboard.attention_description_text",
    "dashboard.attention_meta_text",
    "dashboard.attention_badge_surface",
    "dashboard.attention_badge_text",
    "dashboard.attention_badge_border",
    "dashboard.attention_badge_ok_surface",
    "dashboard.attention_badge_ok_text",
    "dashboard.attention_badge_ok_border",
    "dashboard.attention_badge_critical_surface",
    "dashboard.attention_badge_critical_text",
    "dashboard.attention_badge_critical_border",
    "dashboard.attention_action_surface",
    "dashboard.attention_action_text",
    "dashboard.attention_action_border",
    "dashboard.attention_action_hover_surface",
    "dashboard.attention_action_hover_text",
    "dashboard.attention_action_hover_border",
    "dashboard.attention_action_disabled_surface",
    "dashboard.attention_action_disabled_text",
    "dashboard.attention_action_disabled_border",
    "dashboard.attention_pace_surface",
    "dashboard.attention_pace_border",
    "dashboard.attention_pace_icon_surface",
    "dashboard.attention_pace_icon_text",
    "dashboard.attention_pace_icon_border",
    "dashboard.attention_pace_badge_surface",
    "dashboard.attention_pace_badge_text",
    "dashboard.attention_pace_badge_border",
    "dashboard.attention_forecast_action_surface",
    "dashboard.attention_forecast_action_text",
    "dashboard.attention_forecast_action_border",
    "dashboard.attention_forecast_action_hover_surface",
    "dashboard.attention_forecast_action_hover_text",
    "dashboard.attention_forecast_action_hover_border",
    "dashboard.attention_forecast_action_disabled_border",
    "dashboard.attention_footer_surface",
    "dashboard.attention_footer_border",
    "dashboard.attention_footer_item_text",
    "dashboard.attention_footer_hint_text",
    "dashboard.planning_full_panel_surface",
    "dashboard.planning_full_panel_border",
    "dashboard.planning_full_toggle_text",
    "dashboard.planning_full_toggle_hover_surface",
    "dashboard.planning_full_subtitle_text",
    "dashboard.planning_full_subsection_title_text",
    "dashboard.planning_full_subsection_hint_text",
    "dashboard.planning_full_micro_label_text",
    "dashboard.planning_full_box_surface",
    "dashboard.planning_full_box_border",
    "dashboard.planning_full_item_title_text",
    "dashboard.planning_full_daily_value_text",
    "dashboard.planning_full_daily_progress_track",
    "dashboard.planning_full_daily_progress_fill",
    "dashboard.planning_full_progress_complete_fill",
    "dashboard.planning_full_hint_text",
    "dashboard.planning_full_hint_complete_text",
    "dashboard.planning_full_total_badge_surface",
    "dashboard.planning_full_total_badge_text",
    "dashboard.planning_full_total_badge_border",
    "dashboard.planning_full_inset_surface",
    "dashboard.planning_full_inset_border",
    "dashboard.planning_full_day_today_surface",
    "dashboard.planning_full_day_today_border",
    "dashboard.planning_full_day_light_surface",
    "dashboard.planning_full_day_light_border",
    "dashboard.planning_full_day_moderate_surface",
    "dashboard.planning_full_day_moderate_border",
    "dashboard.planning_full_day_high_surface",
    "dashboard.planning_full_day_high_border",
    "dashboard.planning_full_day_name_text",
    "dashboard.planning_full_day_today_text",
    "dashboard.planning_full_day_date_text",
    "dashboard.planning_full_day_today_date_text",
    "dashboard.planning_full_day_count_text",
    "dashboard.planning_full_primary_action_text",
    "dashboard.planning_full_primary_action_border",
    "dashboard.planning_full_goal_hover_border",
    "dashboard.planning_full_journey_hover_border",
    "dashboard.planning_full_journey_paused_text",
    "dashboard.planning_full_journey_paused_border",
    "dashboard.planning_full_journey_ended_text",
    "dashboard.planning_full_journey_ended_border",
    "dashboard.planning_full_auto_hover_border",
    "dashboard.planning_full_auto_active_border",
    "dashboard.planning_full_auto_active_hover_border",
    "dashboard.planning_full_summary_text",
    "dashboard.planning_full_summary_border",
    "dashboard.planning_full_summary_hover_text",
    "dashboard.planning_full_summary_hover_border",
    "dashboard.planning_full_summary_pressed_text",
    "dashboard.planning_full_summary_pressed_border",
    "dashboard.planning_full_redistribute_text",
    "dashboard.planning_full_redistribute_border",
    "dashboard.planning_full_redistribute_hover_text",
    "dashboard.planning_full_redistribute_hover_border",
    "dashboard.planning_full_redistribute_pressed_text",
    "dashboard.planning_full_redistribute_pressed_border",
    "dashboard.planning_full_redistribute_suggest_text",
    "dashboard.planning_full_redistribute_suggest_border",
    "dashboard.planning_full_redistribute_suggest_hover_text",
    "dashboard.planning_full_redistribute_suggest_hover_border",
    "dashboard.planning_full_week_period_text",
    "dashboard.planning_full_week_status_off_surface",
    "dashboard.planning_full_week_status_off_text",
    "dashboard.planning_full_week_status_off_border",
    "dashboard.planning_full_week_status_active_surface",
    "dashboard.planning_full_week_status_active_text",
    "dashboard.planning_full_week_status_active_border",
    "dashboard.planning_full_week_status_attention_surface",
    "dashboard.planning_full_week_status_attention_text",
    "dashboard.planning_full_week_status_attention_border",
    "dashboard.planning_full_week_status_done_surface",
    "dashboard.planning_full_week_status_done_text",
    "dashboard.planning_full_week_status_done_border",
    "dashboard.planning_full_empty_border",
    "dashboard.planning_full_empty_title_text",
    "dashboard.planning_full_metric_title_text",
    "dashboard.planning_full_metric_value_text",
    "dashboard.planning_full_metric_hint_text",
    "dashboard.planning_full_metric_track",
    "dashboard.planning_full_metric_border",
    "dashboard.study_questions_panel_surface",
    "dashboard.study_questions_panel_border",
    "dashboard.study_questions_header_icon_surface",
    "dashboard.study_questions_header_icon_text",
    "dashboard.study_questions_header_icon_border",
    "dashboard.study_questions_toggle_text",
    "dashboard.study_questions_toggle_hover_surface",
    "dashboard.study_questions_subtitle_text",
    "dashboard.study_questions_foundation_text",
    "dashboard.study_questions_review_border",
    "dashboard.study_questions_adaptive_surface",
    "dashboard.study_questions_adaptive_border",
    "dashboard.study_questions_simulation_border",
    "dashboard.study_questions_recovery_border",
    "dashboard.study_questions_review_icon_surface",
    "dashboard.study_questions_review_icon_text",
    "dashboard.study_questions_review_icon_border",
    "dashboard.study_questions_strategy_icon_surface",
    "dashboard.study_questions_strategy_icon_text",
    "dashboard.study_questions_strategy_icon_border",
    "dashboard.study_questions_simulation_icon_surface",
    "dashboard.study_questions_simulation_icon_text",
    "dashboard.study_questions_simulation_icon_border",
    "dashboard.study_questions_title_text",
    "dashboard.study_questions_review_count_text",
    "dashboard.study_questions_description_text",
    "dashboard.study_questions_review_detail_text",
    "dashboard.study_questions_criteria_text",
    "dashboard.study_questions_assessment_badge_surface",
    "dashboard.study_questions_assessment_badge_text",
    "dashboard.study_questions_assessment_badge_border",
    "dashboard.study_questions_assessment_stat_surface",
    "dashboard.study_questions_assessment_stat_border",
    "dashboard.study_questions_assessment_stat_label_text",
    "dashboard.study_questions_assessment_stat_value_text",
    "dashboard.study_questions_subtle_surface",
    "dashboard.study_questions_subtle_text",
    "dashboard.study_questions_subtle_border",
    "dashboard.study_questions_subtle_hover_surface",
    "dashboard.study_questions_subtle_hover_text",
    "dashboard.study_questions_subtle_hover_border",
    "dashboard.study_questions_adaptive_action_text",
    "dashboard.study_questions_adaptive_action_border",
    "dashboard.study_questions_adaptive_action_hover_text",
    "dashboard.study_questions_adaptive_action_hover_border",
    "dashboard.study_questions_simulation_action_text",
    "dashboard.study_questions_simulation_action_border",
    "dashboard.study_questions_simulation_action_hover_text",
    "dashboard.study_questions_simulation_action_hover_border",
    "dashboard.study_questions_manual_footer_surface",
    "dashboard.study_questions_manual_footer_border",
    "dashboard.study_questions_manual_badge_surface",
    "dashboard.study_questions_manual_badge_text",
    "dashboard.study_questions_manual_badge_border",
    "dashboard.study_questions_manual_text",
    "dashboard.disciplines_header_surface",
    "dashboard.disciplines_header_border",
    "dashboard.disciplines_toggle_text",
    "dashboard.disciplines_toggle_hover_surface",
    "dashboard.disciplines_edit_surface",
    "dashboard.disciplines_edit_text",
    "dashboard.disciplines_edit_border",
    "dashboard.disciplines_edit_hover_surface",
    "dashboard.disciplines_edit_hover_text",
    "dashboard.disciplines_edit_hover_border",
    "dashboard.disciplines_edit_pressed_surface",
    "dashboard.disciplines_edit_pressed_border",
    "dashboard.disciplines_button_surface",
    "dashboard.disciplines_button_text",
    "dashboard.disciplines_button_border",
    "dashboard.disciplines_button_hover_surface",
    "dashboard.disciplines_button_hover_text",
    "dashboard.disciplines_button_hover_border",
    "dashboard.disciplines_disabled_surface",
    "dashboard.disciplines_disabled_text",
    "dashboard.disciplines_disabled_border",
    "dashboard.planning_arc_track",
    "dashboard.planning_arc_fill",
    "dashboard.planning_arc_text",
    "dashboard.quality_donut_track_dark",
    "dashboard.quality_donut_track_light",
    "dashboard.quality_donut_fill",
    "navigation.command_canvas",
    "navigation.command_title_text",
    "navigation.command_meta_text",
    "navigation.command_shortcut_surface",
    "navigation.command_shortcut_text",
    "navigation.command_shortcut_border",
    "navigation.command_input_surface",
    "navigation.command_input_text",
    "navigation.command_input_border",
    "navigation.command_input_selection",
    "navigation.command_input_focus_border",
    "navigation.command_results_surface",
    "navigation.command_results_text",
    "navigation.command_results_border",
    "navigation.command_results_selection_surface",
    "navigation.command_results_selection_text",
    "navigation.command_results_divider",
    "navigation.command_header_surface",
    "navigation.command_header_text",
    "navigation.command_header_border",
    "navigation.back_text",
    "navigation.back_border",
    "navigation.back_hover_text",
    "navigation.back_hover_border",
    # Central de Questões — faixa de inventário (piloto cromático)
    "questions_center.inventory_surface",
    "questions_center.inventory_border",
    "questions_center.inventory_value_text",
    "questions_center.inventory_label_text",
    "questions_center.inventory_divider",
    "questions_center.workspace_surface",
    "questions_center.workspace_border",
    "questions_center.filter_bar_surface",
    "questions_center.filter_bar_border",
    "questions_center.admin_title_text",
    "questions_center.admin_description_text",
    "questions_center.list_title_text",
    "questions_center.list_description_text",
    "questions_center.menu_surface",
    "questions_center.menu_text",
    "questions_center.menu_border",
    "questions_center.menu_hover_surface",
    "questions_center.menu_hover_border",
    "questions_center.menu_hover_text",
    "questions_center.analysis_surface",
    "questions_center.analysis_text",
    "questions_center.analysis_border",
    "questions_center.analysis_hover_surface",
    "questions_center.analysis_hover_border",
    "questions_center.analysis_checked_surface",
    "questions_center.analysis_checked_text",
    "questions_center.analysis_checked_border",
    "questions_center.analysis_disabled_surface",
    "questions_center.analysis_disabled_text",
    "questions_center.analysis_disabled_border",
    "questions_center.tree_disabled_discipline_text",
    "table_highlight.inactive_text",
    "table_highlight.inactive_surface",
    "statistics_tabs.bar_surface",
    "statistics_tabs.bar_border",
    "statistics_tabs.tab_surface",
    "statistics_tabs.tab_text",
    "statistics_tabs.tab_border",
    "statistics_tabs.hover_surface",
    "statistics_tabs.hover_text",
    "statistics_tabs.hover_border",
    "statistics_tabs.selected_surface",
    "statistics_tabs.selected_text",
    "statistics_tabs.selected_border",
    "statistics_tabs.pane_border",
    "statistics_tabs.pane_surface",
    "admin_shared.filter_bar_surface",
    "admin_shared.filter_bar_border",
    "reports.period_surface",
    "reports.period_text",
    "reports.period_border",
    "reports.comparison_surface",
    "reports.comparison_border",
    "reports.metric_surface",
    "reports.metric_border",
    "reports.value_text",
    "reports.trend_positive_text",
    "reports.trend_negative_text",
    "reports.trend_neutral_text",
    # Relatório Estratégico V1 — valores semânticos de componente
    "strategic_report.action_border",
    "strategic_report.action_surface",
    "strategic_report.action_text",
    "strategic_report.evolution_border",
    "strategic_report.evolution_surface",
    "strategic_report.evolution_value_text",
    "strategic_report.frame_emphasis_border",
    "strategic_report.metric_border",
    "strategic_report.metric_detail_text",
    "strategic_report.metric_label_text",
    "strategic_report.metric_surface",
    "strategic_report.metric_value_text",
    "strategic_report.panel_border",
    "strategic_report.panel_surface",
    "strategic_report.prep_attention_text",
    "strategic_report.prep_building_text",
    "strategic_report.prep_good_text",
    "strategic_report.prep_insufficient_text",
    "strategic_report.prep_shared_warning_text",
    "strategic_report.prep_strong_text",
    "strategic_report.risk_high_border",
    "strategic_report.risk_high_surface",
    "strategic_report.risk_high_text",
    "strategic_report.risk_low_border",
    "strategic_report.risk_low_surface",
    "strategic_report.risk_low_text",
    "strategic_report.risk_medium_border",
    "strategic_report.risk_medium_surface",
    "strategic_report.risk_medium_text",
    "strategic_report.section_title_text",
    "strategic_report.subtitle_text",
    "strategic_report.table_border",
    "strategic_report.table_surface",
    "strategic_report.title_text",
    "strategic_report.trend_negative_text",
    "strategic_report.trend_neutral_text",
    "strategic_report.trend_positive_text",
    "my_evolution.shell_surface",
    "my_evolution.title_text",
    "my_evolution.insight_surface",
    "my_evolution.insight_border",
    "my_evolution.insight_positive_surface",
    "my_evolution.insight_positive_border",
    "my_evolution.insight_attention_surface",
    "my_evolution.insight_attention_border",
    "my_evolution.insight_recovery_surface",
    "my_evolution.insight_recovery_border",
    "my_evolution.insight_label_text",
    "my_evolution.insight_value_text",
    "my_evolution.insight_detail_text",
    "question_history.card_surface",
    "question_history.card_border",
    "question_history.content_surface",
    "question_history.content_border",
    "question_history.tab_surface",
    "question_history.tab_text",
    "question_history.tab_selected_surface",
    "question_history.tab_selected_text",
    "question_history.tab_selected_border",
    "question_history.rule_surface",
    "question_history.rule_text",
    "question_history.rule_border",
    "question_history.retry_surface",
    "question_history.retry_text",
    "question_history.retry_border",
    "question_history.retry_hover_surface",
    "question_history.retry_hover_border",
    "question_history.review_surface",
    "question_history.review_text",
    "question_history.review_border",
    "question_history.review_hover_surface",
    "error_bank.distribution_surface",
    "error_bank.distribution_border",
    "error_bank.detail_surface",
    "error_bank.detail_text",
    "error_bank.detail_border",
    "error_bank.explanation_text",
    "question_import.structure_surface",
    "question_import.structure_border",
    "question_import.file_title_text",
    "question_import.file_meta_text",
    "question_import.hint_surface",
    "question_import.hint_text",
    "question_import.hint_border",
    "question_import.vpq_metadata_text",
    "question_import.vpq_link_default_text",
    "question_import.vpq_details_text",
    "question_import.editor_surface",
    "question_import.editor_text",
    "question_import.editor_border",
    "question_import.editor_selection_surface",
    "question_import.editor_focus_border",
    "question_import.vpq_integrity_surface",
    "question_import.vpq_integrity_border",
    "question_import.vpq_warning_surface",
    "question_import.vpq_warning_border",
    "question_import.vpq_review_surface",
    "question_import.vpq_review_border",
    "question_import.vpq_integrity_result_text",
    "question_import.vpq_warning_result_text",
    "question_import.vpq_review_result_text",
    "question_import.vpq_link_ok_text",
    "question_import.vpq_link_warning_text",
    "question_import.status_surface",
    "question_import.status_border",
    "question_import.badge_surface",
    "question_import.badge_text",
    "question_import.result_default_text",
    "question_management.shared_table_surface",
    "question_management.shared_table_border",
    "admin_shared.danger_surface",
    "admin_shared.danger_text",
    "admin_shared.danger_border",
    "admin_shared.danger_hover_surface",
    "admin_shared.danger_hover_border",
    "admin_shared.filter_count_surface",
    "admin_shared.filter_count_text",
    "admin_shared.filter_count_border",
    "admin_shared.primary_base_surface",
    "admin_shared.primary_base_text",
    "admin_shared.primary_base_border",
    "admin_shared.primary_base_hover_surface",
    "admin_shared.primary_base_hover_border",
    "admin_shared.primary_group_a_surface",
    "admin_shared.primary_group_a_text",
    "admin_shared.primary_group_a_border",
    "admin_shared.primary_group_a_hover_surface",
    "admin_shared.primary_group_a_hover_border",
    "admin_shared.primary_group_a_hover_text",
    "admin_shared.primary_group_b_surface",
    "admin_shared.primary_group_b_text",
    "admin_shared.primary_group_b_border",
    "admin_shared.primary_group_b_hover_surface",
    "admin_shared.primary_group_b_hover_border",
    "admin_shared.primary_group_b_hover_text",
    "admin_shared.primary_group_c_surface",
    "admin_shared.primary_group_c_text",
    "admin_shared.primary_group_c_border",
    "admin_shared.primary_group_c_hover_surface",
    "admin_shared.primary_group_c_hover_border",
    "admin_shared.primary_group_d_surface",
    "admin_shared.primary_group_d_text",
    "admin_shared.primary_group_d_border",
    "admin_shared.primary_group_d_hover_surface",
    "admin_shared.primary_group_d_hover_border",
    "admin_shared.primary_group_d_hover_text",
    "admin_shared.primary_group_e_border",
    "admin_shared.primary_group_e_hover_border",
    "admin_shared.primary_group_f_border",
    "admin_shared.primary_group_f_hover_border",
    "admin_shared.subtle_base_text",
    "admin_shared.subtle_base_border",
    "admin_shared.subtle_base_hover_surface",
    "admin_shared.subtle_base_hover_border",
    "admin_shared.subtle_group_a_surface",
    "admin_shared.subtle_group_a_text",
    "admin_shared.subtle_group_a_border",
    "admin_shared.subtle_group_a_hover_surface",
    "admin_shared.subtle_group_a_hover_text",
    "admin_shared.subtle_group_a_hover_border",
    "admin_shared.subtle_group_b_surface",
    "admin_shared.subtle_group_b_text",
    "admin_shared.subtle_group_b_border",
    "admin_shared.subtle_group_b_hover_surface",
    "admin_shared.subtle_group_b_hover_text",
    "admin_shared.subtle_group_b_hover_border",
    "admin_shared.subtle_future_text",
    "admin_shared.subtle_future_border",
    "admin_shared.subtle_future_hover_text",
    "admin_shared.subtle_future_hover_border",
    "admin_shared.subtle_planning_surface",
    "admin_shared.subtle_planning_text",
    "admin_shared.subtle_planning_border",
    "admin_shared.subtle_planning_hover_surface",
    "admin_shared.subtle_planning_hover_border",
    # Modais — Rótulo contextual compartilhado V1
    "admin_shared.context_label_text",
    "admin_shared.profile_badge_base_surface",
    "admin_shared.profile_badge_base_text",
    "admin_shared.profile_badge_base_border",
    "admin_shared.profile_badge_context_surface",
    "admin_shared.profile_badge_context_text",
    "admin_shared.profile_badge_context_border",
    "admin_shared.profile_badge_future_text",
    "admin_shared.profile_badge_future_border",
    "question_editor_viewer.card_surface",
    "question_editor_viewer.card_border",
    "question_editor_viewer.section_title_text",
    "question_editor_viewer.alternative_letter_text",
    "question_editor_viewer.alternative_text",
    "question_editor_viewer.alternative_text_futurista",
    "question_editor_viewer.viewer_meta_text",
    "question_editor_viewer.viewer_statement_text",
    "question_editor_viewer.correct_alternative_surface",
    "question_editor_viewer.correct_border",
    "question_editor_viewer.correct_badge_surface",
    "question_editor_viewer.correct_badge_text",
    "question_editor_viewer.integrity_notice_surface",
    "question_editor_viewer.integrity_notice_text",
    "question_editor_viewer.integrity_notice_border",
    "question_editor_viewer.snapshot_notice_surface",
    "question_editor_viewer.snapshot_notice_text",
    "question_editor_viewer.snapshot_notice_border",
    "question_editor_viewer.snapshot_legacy_surface",
    "question_editor_viewer.snapshot_legacy_text",
    "question_editor_viewer.snapshot_legacy_border",
    "question_editor_viewer.archived_notice_surface",
    "question_editor_viewer.archived_notice_text",
    "question_editor_viewer.archived_notice_border",
    "card.dialog_surface",
    "card.dialog_border",
    "card.metric_surface",
    "card.metric_border",
    "card.mini_stat_surface",
    "card.mini_stat_border",
    "card.metric_label_text",
    "card.metric_value_text",
    "card.study_action_border",
    "card.study_action_review_border",
    "card.study_action_adaptive_border",
    "card.evolution_stat_border",
    "card.evolution_stat_label_text",
    "card.evolution_stat_value_text",
    "card.evolution_stat_detail_text",
    "system_status.canvas", "system_status.border", "system_status.surface",
    "system_status.surface_border", "system_status.text_primary", "system_status.text_status",
    "system_status.text_secondary", "system_status.text_accent", "system_status.progress_track",
    "system_status.progress_border", "system_status.progress_fill",
    "startup.logo_surface", "startup.logo_border", "startup.subtitle_text",
    "startup.footer_text", "startup.logo_fallback", "startup.progress_pulse",
    "task_indicator.mark_surface", "task_indicator.mark_border", "task_indicator.mark_text",
)

_COMPONENT_GRADIENT_PATHS = (
    # Modais — Detalhes do Tópico V1
    "modal_topic.domain_bar_modern_chunk_surface_gradient",
    "modal_topic.next_step_card_surface_gradient",
    "modal_topic.study_button_hover_surface_gradient",
    "modal_topic.study_button_surface_gradient",

    "strategic_report.frame_gradient", "strategic_report.action_gradient",
    "answer.selected_gradient", "answer.correct_gradient", "answer.incorrect_gradient",
    "answer.struck_gradient",
    "progress.fill_gradient", "session.overview_gradient", "session.statement_gradient",
    "session.action_panel_gradient",
    "summary.adaptive_gradient", "summary.effectiveness_gradient",
    "focus_mode.action_gradient", "focus_mode.action_hover_gradient",
    "post_focus.primary_gradient", "pause.primary_gradient", "game.primary_gradient",
    "dashboard.topbar_gradient", "dashboard.nav_gradient", "dashboard.nav_hover_gradient",
    "dashboard.focus_card_gradient", "dashboard.focus_action_gradient", "dashboard.focus_action_hover_gradient", "dashboard.planning_card_gradient", "dashboard.planning_progress_gradient",
    "dashboard.recommendation_card_gradient", "dashboard.recommendation_icon_gradient", "dashboard.recommendation_primary_gradient", "dashboard.recommendation_primary_hover_gradient", "dashboard.progress_card_gradient", "dashboard.progress_fill_gradient", "dashboard.quick_access_gradient", "dashboard.quick_toolbar_gradient", "dashboard.quick_toolbar_hover_gradient", "dashboard.quick_pause_gradient", "dashboard.quick_pause_hover_gradient",
    "dashboard.overview_card_gradient", "dashboard.projection_action_gradient", "dashboard.projection_action_hover_gradient",
    "dashboard.planning_full_primary_action_gradient",
    "dashboard.planning_full_primary_action_hover_gradient",
    "dashboard.planning_full_journey_hover_gradient",
    "dashboard.planning_full_journey_paused_gradient",
    "dashboard.planning_full_journey_ended_gradient",
    "dashboard.planning_full_auto_active_gradient",
    "dashboard.planning_full_auto_active_hover_gradient",
    "dashboard.planning_full_summary_gradient",
    "dashboard.planning_full_summary_hover_gradient",
    "dashboard.planning_full_summary_pressed_gradient",
    "dashboard.planning_full_redistribute_gradient",
    "dashboard.planning_full_redistribute_hover_gradient",
    "dashboard.planning_full_redistribute_pressed_gradient",
    "dashboard.planning_full_redistribute_suggest_gradient",
    "dashboard.planning_full_redistribute_suggest_hover_gradient",
    "dashboard.planning_full_metric_progress_gradient",
    "dashboard.planning_full_metric_progress_complete_gradient",
    "dashboard.study_questions_base_card_gradient",
    "dashboard.study_questions_simulation_card_gradient",
    "dashboard.study_questions_adaptive_action_gradient",
    "dashboard.study_questions_adaptive_action_hover_gradient",
    "dashboard.study_questions_simulation_action_gradient",
    "dashboard.study_questions_simulation_action_hover_gradient",
    "navigation.back_surface_gradient", "navigation.back_hover_surface_gradient",
    "card.study_action_surface_gradient", "card.study_action_adaptive_surface_gradient",
    "card.evolution_stat_surface_gradient",
    "admin_shared.primary_group_e_gradient", "admin_shared.primary_group_e_hover_gradient",
    "admin_shared.primary_group_f_gradient", "admin_shared.primary_group_f_hover_gradient",
    "admin_shared.subtle_group_c_gradient", "admin_shared.subtle_group_c_hover_gradient",
    "admin_shared.subtle_group_d_gradient", "admin_shared.subtle_group_d_hover_gradient", "admin_shared.profile_badge_future_gradient",
    "startup.progress_gradient", "startup.shimmer_gradient",
)

FIXED_TOKEN_PATHS = frozenset(
    path
    for path in (*_COMPONENT_COLOR_PATHS, *_COMPONENT_GRADIENT_PATHS)
    if path.startswith(("system_status.", "startup.", "task_indicator."))
)


def _specs(paths: tuple[str, ...], level: TokenLevel, kind: TokenKind) -> tuple[TokenSpec, ...]:
    return tuple(TokenSpec(path, level, kind) for path in paths)


SEMANTIC_TOKENS = (
    *_specs(_SEMANTIC_COLOR_PATHS, TokenLevel.SEMANTIC, TokenKind.COLOR),
    *_specs(_SEMANTIC_GRADIENT_PATHS, TokenLevel.SEMANTIC, TokenKind.GRADIENT),
)
COMPONENT_TOKENS = (
    *_specs(_COMPONENT_COLOR_PATHS, TokenLevel.COMPONENT, TokenKind.COLOR),
    *_specs(_COMPONENT_GRADIENT_PATHS, TokenLevel.COMPONENT, TokenKind.GRADIENT),
)
ALL_TOKENS = (*SEMANTIC_TOKENS, *COMPONENT_TOKENS)

_TOKEN_INDEX: Mapping[str, TokenSpec] = MappingProxyType({token.path: token for token in ALL_TOKENS})
if len(_TOKEN_INDEX) != len(ALL_TOKENS):
    raise RuntimeError("O contrato contém caminhos de token duplicados.")


def token_spec(path: str) -> TokenSpec:
    try:
        return _TOKEN_INDEX[path]
    except KeyError as exc:
        raise KeyError(f"Token inexistente no contrato: {path!r}") from exc


def iter_tokens(
    *, level: TokenLevel | None = None, kind: TokenKind | None = None
) -> Iterator[TokenSpec]:
    return (
        token
        for token in ALL_TOKENS
        if (level is None or token.level is level) and (kind is None or token.kind is kind)
    )


SEMANTIC_TOKEN_COUNT = len(SEMANTIC_TOKENS)
COMPONENT_TOKEN_COUNT = len(COMPONENT_TOKENS)
